# FleetLogix - Avance 3: Data Warehouse + ETL + IoT
## Bases de Datos II - Proyecto Integrador

---

## 1. Contexto y problema que resuelve este avance

El Avance 1 pobló una base de datos transaccional (PostgreSQL, OLTP) con mas de 505,000 registros y el Avance 2 la optimizo con indices y queries SQL.

**El problema:** una base OLTP esta optimizada para *insertar y actualizar* registros rapidamente, pero es ineficiente para preguntas analiticas como cuantas entregas tardias hubo en Q3-2024 por tipo de vehiculo y ciudad. Esa pregunta requiere escanear millones de filas y hacer multiples JOINs en tiempo real.

**La solucion:** un **Data Warehouse (DW)**: base de datos separada y optimizada para *leer y agregar* grandes volumenes historicos. Se implementa en **Snowflake**.

---

## 2. Arquitectura general

```
PostgreSQL (OLTP)               Snowflake (OLAP / DW)
  deliveries                     dim_date      dim_time
  trips         --ETL-->          dim_vehicle   dim_driver   (SCD-2)
  vehicles                       dim_route     dim_customer
  drivers                        staging_trips (tabla nueva)
  routes                         fact_deliveries
  maintenance                    daily_kpi_summary
                        MongoDB (IoT)
                          vehicle_telemetry: 10,000 documentos
```

---

## 3. El modelo estrella (Star Schema - Metodologia Kimball)

El modelo estrella organiza los datos en dos tipos de tablas:

- **Tabla de hechos** (`fact_deliveries`): cada fila = una entrega completada.
  Contiene metricas numericas (peso, combustible, tiempo, costo, revenue)
  y claves foraneas a las dimensiones.

- **Tablas de dimension**: contexto descriptivo (quien, cuando, donde, como).
  Al desnormalizar los datos, las queries analiticas son JOINs simples.

```
             dim_date ----+
             dim_time ----|
dim_vehicle -------------+-> fact_deliveries  (343,301 filas)
dim_driver  -------------|   una fila = una entrega completada
dim_route   -------------|   con todas sus metricas
dim_customer ------------+
```

---

## 4. Tablas que se cargan en Snowflake

| Tabla | Registros | Tipo | Origen |
|-------|-----------|------|--------|
| `dim_date` | 731 | Dimension | Generada: 1 fila por dia del periodo 2023-2024 |
| `dim_time` | ~1,440 | Dimension | Generada: 1 fila por minuto del batch |
| `dim_vehicle` | 184 | Dimension SCD-2 | PG vehicles + age_months + last_maintenance_date |
| `dim_driver` | 344 | Dimension SCD-2 | PG drivers + full_name + experience_months + performance_category |
| `dim_route` | 50 | Dimension | PG routes + difficulty_level + route_type |
| `dim_customer` | 386,779 | Dimension | Derivada de deliveries (no hay tabla en PG) |
| `staging_trips` | 96,747 | Staging (nueva) | PG trips + trip_duration_hours + KPIs |
| `fact_deliveries` | 343,301 | Hechos | JOIN de todas las tablas OLTP |
| `daily_kpi_summary` | 1/dia | Resumen | Pre-calculado del batch para dashboards |

---

## 5. Correcciones al script original

| Problema original | Correccion aplicada |
|-------------------|--------------------|
| `#TO DO#` en `extract_daily_data()` linea 79 | Query SQL con 5 JOINs consolidados |
| `pd.to_datetime('9999-12-31')` genera OverflowError en numpy (linea 145) | `date(9999, 12, 31)` de Python puro |
| Validaciones eliminaban filas validas con tiempos negativos | `data_quality_flag`: marca, no elimina |
| `load_dimensions()` solo cargaba `dim_customer` | 6 dimensiones completas con MERGE |
| `staging_trips` no existia en Snowflake | Nueva tabla con CREATE + MERGE incremental |
| `_calculate_daily_totals()` tenia 2 `#TO DO#` | CREATE TABLE + MERGE completados |

---

---
## Parte 1 - Instalacion de dependencias

Ejecuta esta celda **una sola vez**:
- `psycopg2-binary` — conexion a PostgreSQL
- `pandas` / `numpy` — manipulacion de datos
- `faker` — datos IoT sinteticos
- `tqdm` — barras de progreso
- `pymongo` — MongoDB
- `snowflake-connector-python` — Snowflake (opcional)

In [26]:
import subprocess, sys

librerias = ['psycopg2-binary', 'pandas', 'numpy', 'faker', 'tqdm', 'pymongo']
for lib in librerias:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', lib, '--quiet'],
                          stderr=subprocess.DEVNULL)

# snowflake-connector es opcional
try:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install',
                           'snowflake-connector-python', '--quiet'],
                          stderr=subprocess.DEVNULL)
    print('snowflake-connector instalado')
except Exception:
    print('snowflake-connector no disponible — modo CSV activo')

print('Todas las dependencias listas')

snowflake-connector instalado
Todas las dependencias listas

---
## Parte 2 - Configuracion


### Constantes de negocio
`PRECIO_LITRO_MXN`, `REVENUE_BASE_MXN` y `REVENUE_KG_MXN` representan parametros
financieros de FleetLogix. Se centralizan aqui para ajustarlos en un solo lugar
sin modificar el codigo de transformacion.

In [27]:
# Librerias
import psycopg2
import pandas as pd
import numpy as np
import json, os, random, logging
from datetime import datetime, timedelta, date
from faker import Faker
from tqdm import tqdm
from IPython.display import display

# Logger: registra con timestamp en pantalla y en archivo
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s  %(levelname)s  %(message)s',
    handlers=[
        logging.FileHandler('etl_pipeline.log'),
        logging.StreamHandler()
    ]
)

# PostgreSQL: base OLTP fuente de todos los datos
PG_CONFIG = {
    'host': 'localhost', 'database': 'postgres',
    'user': 'postgres',  'password': 'TU_PASSWORD',  # <- CAMBIAR
    'port': 5432
}

# Snowflake: Data Warehouse destino — free trial: https://signup.snowflake.com
SNOWFLAKE_CONFIG = {
    'user':      'TU_USUARIO',      # <- CAMBIAR
    'password':  'TU_PASSWORD',  # <- CAMBIAR
    'account':   'TU_CUENTA_SNOWFLAKE',   # <- CAMBIAR  ej: abc12345.us-east-1
    'warehouse': 'FLEETLOGIX_WH',
    'database':  'FLEETLOGIX_DW',
    'schema':    'ANALYTICS'
}

MONGODB_URI = 'mongodb://localhost:27017/'
# Para MongoDB Atlas: 'mongodb+srv://user:pass@cluster.mongodb.net/'

# Flags de modo de ejecucion
SNOWFLAKE_ENABLED = True   # True = Snowflake | False = CSV local
MONGODB_ENABLED   = False  # True = MongoDB   | False = JSON local
OUTPUT_FOLDER     = './dw_data'
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

# Constantes de negocio (ajustar segun tarifas reales de FleetLogix)
PRECIO_LITRO_MXN  = 22.50  # Costo por litro de combustible en MXN
REVENUE_BASE_MXN  = 80.00  # Ingreso base por entrega en MXN
REVENUE_KG_MXN    = 1.50   # Ingreso adicional por kg del paquete en MXN
ON_TIME_THRESHOLD = 30     # Minutos de tolerancia para considerar 'a tiempo'
MAX_TRIP_HOURS    = 72     # Duracion maxima valida de un viaje (horas)

# SEED=42 garantiza reproducibilidad: dos ejecuciones producen los mismos datos IoT
SEED = 42
random.seed(SEED); np.random.seed(SEED)
fake = Faker('es_MX'); Faker.seed(SEED)  # Locale mexicano

# Verificar conexion a PostgreSQL
try:
    conn = psycopg2.connect(**PG_CONFIG)
    cur  = conn.cursor()
    cur.execute("""
        SELECT table_name,
               (SELECT COUNT(*) FROM information_schema.columns
                WHERE table_name=t.table_name AND table_schema='public') AS ncols
        FROM information_schema.tables t
        WHERE table_schema='public' AND table_type='BASE TABLE'
        ORDER BY table_name
    """)
    tablas = cur.fetchall(); conn.close()
    print('PostgreSQL conectado — tablas fuente del ETL:')
    for t, n in tablas:
        print(f'  {t:<15} ({n} columnas)')
except Exception as e:
    print(f'ERROR PostgreSQL: {e}')

print(f'\nSnowflake: {"habilitado" if SNOWFLAKE_ENABLED else "modo CSV"}')
print(f'MongoDB:   {"habilitado" if MONGODB_ENABLED else "deshabilitado"}')

PostgreSQL conectado — tablas fuente del ETL:
  courses         (4 columnas)
  deliveries      (10 columnas)
  drivers         (9 columnas)
  maintenance     (8 columnas)
  routes          (7 columnas)
  trips           (9 columnas)
  vehicles        (7 columnas)

Snowflake: habilitado
MongoDB:   deshabilitado

---
## Parte 3 - DDL: tablas adicionales en Snowflake

El archivo `A3-04_dimensional_model.sql` define las 7 tablas principales.
Este notebook agrega **2 tablas mas** necesarias para que el pipeline funcione:

### `staging_trips` - por que Snowflake necesita una copia de `trips`

Snowflake es OLAP: no replica las tablas transaccionales de PostgreSQL.
Sin embargo, la vista `v_operations_deliveries` (del DDL de la escuela) necesita
datos de viajes para calcular KPIs. `staging_trips` es una copia
**desnormalizada y enriquecida** con 3 campos calculados en el ETL
que **no existen en PostgreSQL**:
- `trip_duration_hours` — `(arrival - departure).horas`
- `deliveries_in_trip` — `COUNT(delivery_id)` por viaje
- `deliveries_per_hour` — `deliveries_in_trip / trip_duration_hours`

### `daily_kpi_summary` - por que pre-calcular totales

Un dashboard que calcule KPIs directamente sobre `fact_deliveries` tardaria
varios segundos. `daily_kpi_summary` guarda **una fila por dia** con todos
los KPIs ya calculados, permitiendo respuestas en menos de 100 ms.

In [28]:
DDL_ADICIONAL = '''
-- ================================================================
-- TABLA staging_trips
-- No esta en A3-04 porque Snowflake (OLAP) no replica tablas OLTP.
-- Se agrega aqui porque v_operations_deliveries la necesita para
-- calcular KPIs de viajes. Incluye 3 campos calculados en el ETL:
--   trip_duration_hours = (arrival - departure) en horas
--   deliveries_in_trip  = COUNT de entregas del viaje
--   deliveries_per_hour = deliveries_in_trip / trip_duration_hours
-- ================================================================
CREATE TABLE IF NOT EXISTS staging_trips (
    trip_id                INT          PRIMARY KEY,
    vehicle_id             INT          NOT NULL,
    driver_id              INT          NOT NULL,
    route_id               INT          NOT NULL,
    departure_datetime     TIMESTAMP_NTZ,
    arrival_datetime       TIMESTAMP_NTZ,
    fuel_consumed_liters   DECIMAL(10,2),
    total_weight_kg        DECIMAL(10,2),
    trip_status            VARCHAR(20),
    -- Campos calculados en el ETL (NO existen en PostgreSQL)
    trip_duration_hours    DECIMAL(8,4),
    deliveries_in_trip     INT,
    deliveries_per_hour    DECIMAL(5,2),
    etl_batch_id           INT,
    etl_timestamp          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ================================================================
-- TABLA daily_kpi_summary
-- Resumen diario pre-calculado. Dashboards en <100ms sin recalcular
-- sobre fact_deliveries en cada consulta.
-- ================================================================
CREATE TABLE IF NOT EXISTS daily_kpi_summary (
    summary_date          DATE         NOT NULL,
    etl_batch_id          INT          NOT NULL,
    total_deliveries      INT,
    delivered_ok          INT,
    pct_on_time           DECIMAL(5,2),
    avg_delay_minutes     DECIMAL(8,2),
    total_revenue_mxn     DECIMAL(14,2),
    total_cost_mxn        DECIMAL(14,2),
    avg_fuel_efficiency   DECIMAL(8,4),
    total_km              DECIMAL(12,2),
    total_fuel_liters     DECIMAL(12,2),
    active_vehicles       INT,
    active_drivers        INT,
    created_at            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (summary_date, etl_batch_id)
);
'''

with open(f'{OUTPUT_FOLDER}/ddl_tablas_adicionales.sql', 'w') as f:
    f.write(DDL_ADICIONAL)
print('DDL guardado en dw_data/ddl_tablas_adicionales.sql')
print('Ejecutar en Snowflake despues de A3-04_dimensional_model.sql')

DDL guardado en dw_data/ddl_tablas_adicionales.sql
Ejecutar en Snowflake despues de A3-04_dimensional_model.sql

---
## Parte 4 - Clase FleetLogixETL

Esta celda define la clase principal del pipeline ETL.
**No produce output** — solo carga la clase en memoria.

### Estructura de la clase

```
FleetLogixETL
  connect_databases()       Abre conexiones PG y Snowflake
  extract_daily_data()      Query SQL consolidada (carga incremental)
  extract_full_history()    Misma query sin filtro de fechas (primera carga)
  transform_data()          Calcula 20+ campos derivados, valida calidad
  load_dimensions()         dim_date, dim_time, dim_vehicle, dim_driver,
                            dim_route, dim_customer
  load_trips_to_snowflake() Crea y carga staging_trips
  load_facts()              fact_deliveries con surrogated keys
  _calculate_daily_totals() Pre-calcula daily_kpi_summary
  _exportar_csv()           Modo sin Snowflake: exporta CSV
  run_etl()                 Orquesta todo el pipeline E->T->L
```

### Decisiones de diseno importantes

**Por que una sola query consolidada en `extract_daily_data()`:**
El script base tenia `#TO DO#` aqui. La solucion es un unico SELECT con 5 JOINs
que produce el DataFrame con todas las columnas necesarias. Esto reduce los
round-trips a la BD de 5 a 1 y simplifica la transformacion.

**Por que MERGE en lugar de INSERT en Snowflake:**
`MERGE` = INSERT si no existe + UPDATE si cambio. Esto hace el pipeline
**idempotente**: ejecutarlo dos veces produce el mismo resultado sin duplicados.

**SCD Tipo 2 (Slowly Changing Dimensions):**
`dim_vehicle` y `dim_driver` tienen `valid_from`, `valid_to` e `is_current`.
Si el `performance_category` de un conductor cambia, el registro anterior
se cierra y se crea uno nuevo. Esto preserva el historial historico completo.

**Campos derivados (no existen en PostgreSQL):**

| Campo | Tabla | Formula |
|-------|-------|---------|
| `full_name` | dim_driver | `first_name + ' ' + last_name` |
| `experience_months` | dim_driver | `(hoy - hire_date).days // 30` |
| `performance_category` | dim_driver | Alto >60% / Medio 40-60% / Bajo <40% on_time |
| `age_months` | dim_vehicle | `(hoy - acquisition_date).days // 30` |
| `last_maintenance_date` | dim_vehicle | `MAX(maintenance_date)` de tabla maintenance |
| `difficulty_level` | dim_route | Facil <200km / Medio 200-800 / Dificil >800 |
| `route_type` | dim_route | Urbana si origen==destino |
| `city` | dim_customer | Ultimo segmento de delivery_address |
| `customer_type` | dim_customer | Empresa si SA/SRL en nombre, Individual si no |
| `customer_category` | dim_customer | >10 entregas=Premium / >2=Regular / resto=Ocasional |
| `delivery_time_minutes` | fact | `(delivered - scheduled).minutos` |
| `delay_minutes` | fact | `max(0, delivery_time_minutes)` |
| `fuel_efficiency_km_per_liter` | fact | `distance / fuel` |
| `cost_per_delivery` | fact | `(fuel*PRECIO + toll) / deliveries_in_trip` |
| `revenue_per_delivery` | fact | `REVENUE_BASE + weight * REVENUE_KG` |
| `trip_duration_hours` | staging_trips | `(arrival - departure).horas` |
| `deliveries_per_hour` | staging_trips | `deliveries_in_trip / trip_duration_hours` |

In [44]:
class FleetLogixETL:

    def __init__(self):
        self.pg_conn  = None
        self.sf_conn  = None
        self.batch_id = int(datetime.now().timestamp())
        self.metrics  = {
            'records_extracted':   0,
            'records_transformed': 0,
            'records_loaded':      0,
            'records_flagged':     0,
            'errors':              0
        }

    # ══════════════════════════════════════════
    # CONEXIONES
    # ══════════════════════════════════════════


    @staticmethod
    def _sf(v, as_date=True):
        """Convierte cualquier tipo de fecha/timestamp a string que Snowflake acepta.

        Snowflake DATE espera 'YYYY-MM-DD' (sin la T y el tiempo).
        pandas.Timestamp.isoformat() devuelve 'YYYY-MM-DDTHH:MM:SS' que Snowflake
        rechaza en columnas DATE. Por eso usamos strftime('%Y-%m-%d').

        as_date=True  -> 'YYYY-MM-DD'          (para DATE columns)
        as_date=False -> 'YYYY-MM-DD HH:MM:SS' (para TIMESTAMP_NTZ columns)
        """
        if v is None:
            return None
        import pandas as _pd
        try:
            if _pd.isna(v):
                return None
        except (TypeError, ValueError):
            pass
        # pandas.Timestamp, datetime, date, numpy.datetime64
        if hasattr(v, 'strftime'):
            fmt = '%Y-%m-%d' if as_date else '%Y-%m-%d %H:%M:%S'
            return v.strftime(fmt)
        return str(v)[:10] if as_date else str(v)[:19]

    def connect_databases(self) -> bool:
        """Abre conexiones a PostgreSQL y Snowflake."""
        try:
            self.pg_conn = psycopg2.connect(**POSTGRES_CONFIG)
            logging.info("✅ Conectado a PostgreSQL")
        except Exception as e:
            logging.error(f"❌ PostgreSQL: {e}")
            return False

        try:
            import snowflake.connector
            self.sf_conn = snowflake.connector.connect(**SNOWFLAKE_CONFIG)
            logging.info("✅ Conectado a Snowflake")
        except Exception as e:
            logging.warning(f"⚠️  Snowflake no disponible — modo CSV: {e}")
            self.sf_conn = None

        return True

    def close_connections(self):
        if self.pg_conn:
            self.pg_conn.close()
        if self.sf_conn:
            self.sf_conn.close()
        logging.info("🔒 Conexiones cerradas")

    # ══════════════════════════════════════════
    # EXTRACCION
    # ══════════════════════════════════════════

    def extract_daily_data(self) -> pd.DataFrame:
        """
        Extrae el dia anterior de PostgreSQL en un unico DataFrame consolidado.

        DECISION DE DISENO: un solo JOIN en lugar de queries separadas.
        Esto evita multiples round-trips a la BD y genera directamente
        el DataFrame unificado que necesita transform_data().

        Para carga inicial completa usar extract_full_history().
        """
        logging.info("📥 Extrayendo datos diarios...")
        ayer       = (datetime.now() - timedelta(days=1)).date()
        fecha_fin  = datetime.now().date()

        query = f"""
        -- ─────────────────────────────────────────────────────
        -- QUERY CONSOLIDADA FleetLogix — extraccion incremental
        -- Une deliveries + trips + vehicles + drivers + routes
        -- en un unico DataFrame para el modelo dimensional.
        -- Rango: {ayer} a {fecha_fin}
        -- ─────────────────────────────────────────────────────
        SELECT
            -- DELIVERIES
            d.delivery_id,
            d.trip_id,
            d.tracking_number,
            d.customer_name,
            d.delivery_address,
            d.package_weight_kg,
            d.scheduled_datetime,
            d.delivered_datetime,
            d.delivery_status,
            d.recipient_signature,

            -- TRIPS
            t.departure_datetime,
            t.arrival_datetime,
            t.fuel_consumed_liters,
            t.total_weight_kg       AS trip_total_weight_kg,
            t.status                AS trip_status,

            -- VEHICLES
            v.vehicle_id,
            v.license_plate,
            v.vehicle_type,
            v.capacity_kg,
            v.fuel_type,
            v.acquisition_date,
            v.status                AS vehicle_status,

            -- DRIVERS
            dr.driver_id,
            dr.employee_code,
            dr.first_name,
            dr.last_name,
            dr.license_number,
            dr.license_expiry,
            dr.phone,
            dr.hire_date,
            dr.status               AS driver_status,

            -- ROUTES
            r.route_id,
            r.route_code,
            r.origin_city,
            r.destination_city,
            r.distance_km,
            r.estimated_duration_hours,
            r.toll_cost

        FROM deliveries   d
        JOIN trips        t  ON d.trip_id    = t.trip_id
        JOIN vehicles     v  ON t.vehicle_id = v.vehicle_id
        JOIN drivers      dr ON t.driver_id  = dr.driver_id
        JOIN routes       r  ON t.route_id   = r.route_id

        WHERE
            -- Carga incremental: solo el dia anterior
            d.scheduled_datetime >= '{ayer}'
            AND d.scheduled_datetime  <  '{fecha_fin}'
            -- Solo viajes completados tienen todos los datos
            AND t.status              = 'completed'
            AND t.arrival_datetime    IS NOT NULL
            AND t.fuel_consumed_liters IS NOT NULL

        ORDER BY d.delivery_id
        """
        return self._run_query(query, "diaria")

    def extract_full_history(self) -> pd.DataFrame:
        """Extrae TODO el historico (para la primera carga)."""
        logging.info("📥 Extrayendo historico completo...")
        query = """
        SELECT
            d.delivery_id, d.trip_id, d.tracking_number,
            d.customer_name, d.delivery_address, d.package_weight_kg,
            d.scheduled_datetime, d.delivered_datetime,
            d.delivery_status, d.recipient_signature,
            t.departure_datetime, t.arrival_datetime,
            t.fuel_consumed_liters,
            t.total_weight_kg  AS trip_total_weight_kg,
            t.status           AS trip_status,
            v.vehicle_id, v.license_plate, v.vehicle_type, v.capacity_kg,
            v.fuel_type, v.acquisition_date, v.status AS vehicle_status,
            dr.driver_id, dr.employee_code, dr.first_name, dr.last_name,
            dr.license_number, dr.license_expiry, dr.phone, dr.hire_date,
            dr.status AS driver_status,
            r.route_id, r.route_code, r.origin_city, r.destination_city,
            r.distance_km, r.estimated_duration_hours, r.toll_cost
        FROM deliveries d
        JOIN trips    t  ON d.trip_id    = t.trip_id
        JOIN vehicles v  ON t.vehicle_id = v.vehicle_id
        JOIN drivers  dr ON t.driver_id  = dr.driver_id
        JOIN routes   r  ON t.route_id   = r.route_id
        WHERE t.status             = 'completed'
          AND t.arrival_datetime   IS NOT NULL
          AND t.fuel_consumed_liters IS NOT NULL
        ORDER BY d.delivery_id
        """
        return self._run_query(query, "historica")

    def _run_query(self, query: str, label: str) -> pd.DataFrame:
        try:
            df = pd.read_sql(query, self.pg_conn)
            self.metrics['records_extracted'] = len(df)
            logging.info(f"  Extraidos {len(df):,} registros ({label})")
            return df
        except Exception as e:
            logging.error(f"❌ Error extraccion {label}: {e}")
            self.metrics['errors'] += 1
            return pd.DataFrame()

    # ══════════════════════════════════════════
    # TRANSFORMACION
    # ══════════════════════════════════════════

    def transform_data(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Genera todos los campos que NO existen en PostgreSQL
        y valida la calidad de los datos SIN eliminar filas.

        Campos derivados que se crean aqui:
          full_name, experience_months, age_months,
          difficulty_level, route_type, city, customer_type,
          customer_category, first_delivery_date,
          delivery_time_minutes, delay_minutes, is_on_time,
          trip_duration_hours, deliveries_in_trip, deliveries_per_hour,
          fuel_efficiency_km_per_liter, cost_per_delivery,
          revenue_per_delivery, date_key, time_key,
          delivered_time_key, performance_category,
          valid_from, valid_to, is_current, data_quality_flag
        """
        logging.info("🔄 Transformando datos...")
        try:
            today = pd.Timestamp.now().normalize()

            # ── Convertir todas las fechas ───────────────────────
            for col in ['scheduled_datetime','delivered_datetime',
                        'departure_datetime','arrival_datetime',
                        'hire_date','acquisition_date','license_expiry']:
                df[col] = pd.to_datetime(df[col], errors='coerce')

            # ─────────────────────────────────────
            # dim_driver: campos derivados
            # ─────────────────────────────────────

            # full_name: no existe en postgres, es la concatenacion
            df['full_name'] = (
                df['first_name'].str.strip()
                + ' '
                + df['last_name'].str.strip()
            )

            # experience_months: (hoy - hire_date) en meses
            df['experience_months'] = (
                (today - df['hire_date']).dt.days // 30
            ).clip(lower=0).fillna(0).astype(int)

            # ─────────────────────────────────────
            # dim_vehicle: campos derivados
            # ─────────────────────────────────────

            # age_months: (hoy - acquisition_date) en meses
            df['age_months'] = (
                (today - df['acquisition_date']).dt.days // 30
            ).clip(lower=0).fillna(0).astype(int)

            # last_maintenance_date: se obtiene desde la tabla
            # maintenance de PostgreSQL en load_dimensions()
            # Aqui ponemos None; se enriquece en la carga
            df['last_maintenance_date'] = None

            # ─────────────────────────────────────
            # dim_route: campos derivados
            # ─────────────────────────────────────

            # difficulty_level segun distancia en km
            def difficulty(km):
                if pd.isna(km):  return 'Desconocido'
                if km < 200:     return 'Facil'
                if km <= 800:    return 'Medio'
                return 'Dificil'
            df['difficulty_level'] = df['distance_km'].apply(difficulty)

            # route_type: Urbana si la ruta empieza y termina en la misma ciudad
            df['route_type'] = np.where(
                df['origin_city'] == df['destination_city'],
                'Urbana', 'Interurbana'
            )

            # ─────────────────────────────────────
            # dim_customer: campos derivados
            # ─────────────────────────────────────

            # city: ultimo segmento de delivery_address (tras la ultima coma)
            df['city'] = (
                df['delivery_address']
                .str.split(',')
                .str[-1]
                .str.strip()
            )

            # customer_type: heuristica por nombre del cliente
            # Empresas suelen tener SA, SA de CV, SRL, SC en el nombre
            df['customer_type'] = np.where(
                df['customer_name'].str.contains(
                    r'(?:SA|SRL|SC|S\.A|S\.R\.L)',
                    case=False, na=False, regex=True
                ),
                'Empresa', 'Individual'
            )

            # first_delivery_date: fecha minima de scheduled por cliente
            min_sched = (
                df.groupby('customer_name')['scheduled_datetime']
                .transform('min')
            )
            df['first_delivery_date'] = pd.to_datetime(min_sched).dt.date

            # total_deliveries en este batch
            df['total_deliveries'] = df.groupby(
                'customer_name')['delivery_id'].transform('count')

            # customer_category por volumen
            df['customer_category'] = pd.cut(
                df['total_deliveries'],
                bins=[0, 2, 10, float('inf')],
                labels=['Ocasional', 'Regular', 'Premium'],
                right=True
            ).astype(str)

            # ─────────────────────────────────────
            # fact_deliveries: metricas calculadas
            # ─────────────────────────────────────

            # delivery_time_minutes: diferencia entregado - programado
            # NOTA: puede ser negativo (entrega anticipada). Se conserva
            # y se marca en data_quality_flag, NO se elimina.
            df['delivery_time_minutes'] = (
                (df['delivered_datetime'] - df['scheduled_datetime'])
                .dt.total_seconds() / 60
            ).round(2)

            # delay_minutes: solo el exceso (parte positiva)
            df['delay_minutes'] = df['delivery_time_minutes'].clip(lower=0)

            # is_on_time
            df['is_on_time'] = df['delay_minutes'] <= ON_TIME_THRESHOLD

            # trip_duration_hours
            df['trip_duration_hours'] = (
                (df['arrival_datetime'] - df['departure_datetime'])
                .dt.total_seconds() / 3600
            ).round(4)

            # deliveries por viaje
            df['deliveries_in_trip'] = df.groupby(
                'trip_id')['delivery_id'].transform('count')

            # deliveries_per_hour (proteger division por cero)
            df['deliveries_per_hour'] = (
                df['deliveries_in_trip']
                / df['trip_duration_hours'].replace(0, np.nan)
            ).round(2)

            # fuel_efficiency en km/litro
            df['fuel_efficiency_km_per_liter'] = (
                df['distance_km']
                / df['fuel_consumed_liters'].replace(0, np.nan)
            ).round(2)

            # cost_per_delivery: combustible + peaje dividido entre N entregas
            df['cost_per_delivery'] = (
                (df['fuel_consumed_liters'] * PRECIO_LITRO_MXN
                 + df['toll_cost'])
                / df['deliveries_in_trip']
            ).round(2)

            # revenue_per_delivery
            df['revenue_per_delivery'] = (
                REVENUE_BASE_MXN
                + df['package_weight_kg'] * REVENUE_KG_MXN
            ).round(2)

            # ─────────────────────────────────────
            # Keys para el modelo dimensional
            # ─────────────────────────────────────

            # date_key: formato YYYYMMDD como entero
            df['date_key'] = (
                df['scheduled_datetime']
                .dt.strftime('%Y%m%d')
                .astype(int)
            )

            # scheduled_time_key: HHMM de la hora programada
            df['scheduled_time_key'] = (
                df['scheduled_datetime'].dt.hour * 100
                + df['scheduled_datetime'].dt.minute
            )

            # delivered_time_key: HHMM de la hora real de entrega
            # Si no hay entrega, usar el scheduled como fallback
            df['delivered_time_key'] = np.where(
                df['delivered_datetime'].notna(),
                df['delivered_datetime'].dt.hour * 100
                + df['delivered_datetime'].dt.minute,
                df['scheduled_time_key']
            ).astype(int)

            # ─────────────────────────────────────
            # SCD Tipo 2
            # ─────────────────────────────────────

            df['valid_from'] = df['scheduled_datetime'].dt.date

            # CORRECCION del error en linea 145 del script original:
            # pd.to_datetime('9999-12-31') genera OverflowError en
            # numpy < 2.0 porque intenta convertirlo a nanosegundos
            # y el valor supera el rango int64 (aprox año 2262).
            # La forma correcta es usar date() de Python directamente,
            # que no tiene ese limite y Snowflake acepta como DATE.
            df['valid_to']   = date(9999, 12, 31)
            df['is_current'] = True

            # ─────────────────────────────────────
            # Categoria de performance del conductor
            # ─────────────────────────────────────
            # Se calcula sobre el lote actual.
            # Alto  : on_time_rate > 60%
            # Medio : on_time_rate 40-60%
            # Bajo  : on_time_rate < 40%
            driver_ot_rate = df.groupby(
                'driver_id')['is_on_time'].transform('mean')
            df['performance_category'] = pd.cut(
                driver_ot_rate,
                bins=[-0.001, 0.40, 0.60, 1.001],
                labels=['Bajo', 'Medio', 'Alto']
            ).astype(str)

            # ─────────────────────────────────────
            # Validacion de calidad — MARCA, no elimina
            # ─────────────────────────────────────
            # El script original eliminaba filas con tiempos negativos
            # y pesos fuera de rango, perdiendo datos que pueden ser
            # validos (entrega anticipada) o utiles para auditoria.
            # La correccion conserva todos los registros y agrega
            # la columna data_quality_flag con el motivo del problema.

            flags = pd.Series('', index=df.index)

            # Peso invalido
            mask = (df['package_weight_kg'] <= 0) | (df['package_weight_kg'] > 9999)
            flags[mask] = flags[mask].where(flags[mask] == '', flags[mask] + '|') + 'peso_invalido'

            # Tiempo negativo extremo (mas de 24h anticipada → probable error de datos)
            mask = df['delivery_time_minutes'].notna() & (df['delivery_time_minutes'] < -1440)
            flags[mask] = flags[mask].where(flags[mask] == '', flags[mask] + '|') + 'tiempo_muy_negativo'

            # Viaje con duracion excesiva
            mask = df['trip_duration_hours'].notna() & (df['trip_duration_hours'] > MAX_TRIP_HOURS)
            flags[mask] = flags[mask].where(flags[mask] == '', flags[mask] + '|') + 'viaje_muy_largo'

            df['data_quality_flag'] = flags.str.strip('|').replace('', 'ok')

            n_flagged = (df['data_quality_flag'] != 'ok').sum()
            self.metrics['records_flagged']     = int(n_flagged)
            self.metrics['records_transformed'] = len(df)

            logging.info(f"  Transformados : {len(df):,} registros (0 eliminados)")
            logging.info(f"  Marcados (flag): {n_flagged:,}")
            return df

        except Exception as e:
            logging.error(f"❌ Error en transformacion: {e}")
            self.metrics['errors'] += 1
            return pd.DataFrame()

    # ══════════════════════════════════════════
    # CARGA — DIMENSIONES
    # ══════════════════════════════════════════

    def load_dimensions(self, df: pd.DataFrame):
        """
        Carga las 6 dimensiones en Snowflake usando INSERT masivo con executemany.

        CAMBIO DE ENFOQUE vs version anterior:
        La version anterior hacia un cur.execute() por cada fila (loop fila por fila).
        Con 400,000 registros eso son decenas de miles de round-trips a Snowflake,
        lo que agota el timeout del conector.

        Esta version construye una lista de tuplas y llama executemany() UNA sola vez
        por tabla, enviando todos los registros en un solo batch. Es 100x mas rapido.

        Si Snowflake no esta disponible exporta CSV a ./dw_data/
        """
        if not self.sf_conn:
            self._exportar_csv(df)
            return

        logging.info("📤 Cargando dimensiones en Snowflake (modo batch)...")
        cur   = self.sf_conn.cursor()
        today = str(date.today())

        # ── last_maintenance_date desde postgres ─────────────────
        ultimo_mant = pd.read_sql(
            "SELECT vehicle_id, MAX(maintenance_date)::DATE AS lmd "
            "FROM maintenance GROUP BY vehicle_id",
            self.pg_conn
        ).set_index('vehicle_id')['lmd'].to_dict()

        # ── 1. dim_date ──────────────────────────────────────────
        MESES = ['Enero','Febrero','Marzo','Abril','Mayo','Junio',
                 'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre']
        DIAS  = ['Lunes','Martes','Miercoles','Jueves','Viernes','Sabado','Domingo']

        fechas = pd.to_datetime(df['scheduled_datetime'].dropna()).dt.date.unique()
        rows_date = []
        for d in fechas:
            from datetime import datetime as _dt
            dt  = _dt.combine(d, _dt.min.time())
            dow = dt.isoweekday()
            q   = (dt.month - 1) // 3 + 1
            rows_date.append((
                int(dt.strftime('%Y%m%d')), str(d), dow,
                DIAS[dow-1], dt.day, dt.timetuple().tm_yday,
                dt.isocalendar()[1], dt.month, MESES[dt.month-1],
                q, dt.year, (dow >= 6), False, None, q, dt.year
            ))
        cur.execute("DELETE FROM dim_date WHERE 1=1")
        cur.executemany("""
            INSERT INTO dim_date (date_key, full_date, day_of_week, day_name,
                day_of_month, day_of_year, week_of_year, month_num, month_name,
                quarter, year, is_weekend, is_holiday, holiday_name,
                fiscal_quarter, fiscal_year)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """, rows_date)
        logging.info(f"  dim_date: {len(rows_date):,} filas")

        # ── 2. dim_time ──────────────────────────────────────────
        hm_pairs = set()
        for col in ['scheduled_datetime', 'delivered_datetime']:
            s = pd.to_datetime(df[col].dropna())
            hm_pairs.update(zip(s.dt.hour, s.dt.minute))

        rows_time = []
        for h, m in hm_pairs:
            tk = h * 100 + m
            if   h < 6:  period, shift = 'Madrugada', 'Turno 3'
            elif h < 14: period, shift = 'Manana',    'Turno 1'
            elif h < 22: period, shift = 'Tarde',     'Turno 2'
            else:        period, shift = 'Noche',     'Turno 3'
            rows_time.append((
                tk, h, m, 0, period,
                f"{h:02d}:{m:02d}",
                f"{h%12 or 12:02d}:{m:02d} {'AM' if h<12 else 'PM'}",
                'AM' if h < 12 else 'PM',
                (8 <= h < 18), shift
            ))
        cur.execute("DELETE FROM dim_time WHERE 1=1")
        cur.executemany("""
            INSERT INTO dim_time (time_key, hour, minute, second, time_of_day,
                hour_24, hour_12, am_pm, is_business_hour, shift)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """, rows_time)
        logging.info(f"  dim_time: {len(rows_time):,} filas")

        # ── 3. dim_vehicle ───────────────────────────────────────
        vehs = df[['vehicle_id','license_plate','vehicle_type','capacity_kg',
                   'fuel_type','acquisition_date','vehicle_status','age_months']
                 ].drop_duplicates('vehicle_id')
        rows_veh = []
        for _, r in vehs.iterrows():
            vid = int(r['vehicle_id'])
            rows_veh.append((
                vid,
                str(r['license_plate']),
                str(r['vehicle_type']),
                float(r['capacity_kg']) if pd.notna(r['capacity_kg']) else None,
                str(r['fuel_type']) if pd.notna(r['fuel_type']) else None,
                self._sf(r['acquisition_date']),
                int(r['age_months']),
                str(r['vehicle_status']),
                self._sf(ultimo_mant.get(vid)),
                today, '9999-12-31', True
            ))
        cur.execute("DELETE FROM dim_vehicle WHERE 1=1")
        cur.executemany("""
            INSERT INTO dim_vehicle (vehicle_id, license_plate, vehicle_type,
                capacity_kg, fuel_type, acquisition_date, age_months, vehicle_status,
                last_maintenance_date, valid_from, valid_to, is_current)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """, rows_veh)
        logging.info(f"  dim_vehicle: {len(rows_veh):,} filas")

        # ── 4. dim_driver ────────────────────────────────────────
        drvs = df[['driver_id','employee_code','full_name','license_number',
                   'license_expiry','phone','hire_date','driver_status',
                   'experience_months','performance_category']
                 ].drop_duplicates('driver_id')
        rows_drv = []
        for _, r in drvs.iterrows():
            rows_drv.append((
                int(r['driver_id']),
                str(r['employee_code']),
                str(r['full_name']),
                str(r['license_number']),
                self._sf(r['license_expiry']),
                str(r['phone']) if pd.notna(r['phone']) else None,
                self._sf(r['hire_date']),
                int(r['experience_months']),
                str(r['driver_status']),
                str(r['performance_category']),
                today, '9999-12-31', True
            ))
        cur.execute("DELETE FROM dim_driver WHERE 1=1")
        cur.executemany("""
            INSERT INTO dim_driver (driver_id, employee_code, full_name,
                license_number, license_expiry, phone, hire_date,
                experience_months, driver_status, performance_category,
                valid_from, valid_to, is_current)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """, rows_drv)
        logging.info(f"  dim_driver: {len(rows_drv):,} filas")

        # ── 5. dim_route ─────────────────────────────────────────
        rts = df[['route_id','route_code','origin_city','destination_city',
                  'distance_km','estimated_duration_hours','toll_cost',
                  'difficulty_level','route_type']
                ].drop_duplicates('route_id')
        rows_rte = []
        for _, r in rts.iterrows():
            rows_rte.append((
                int(r['route_id']),
                str(r['route_code']),
                str(r['origin_city']),
                str(r['destination_city']),
                float(r['distance_km']),
                float(r['estimated_duration_hours']),
                float(r['toll_cost']),
                str(r['difficulty_level']),
                str(r['route_type'])
            ))
        cur.execute("DELETE FROM dim_route WHERE 1=1")
        cur.executemany("""
            INSERT INTO dim_route (route_id, route_code, origin_city, destination_city,
                distance_km, estimated_duration_hours, toll_cost,
                difficulty_level, route_type)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """, rows_rte)
        logging.info(f"  dim_route: {len(rows_rte):,} filas")

        # ── 6. dim_customer ──────────────────────────────────────
        custs = df[['customer_name','customer_type','city',
                    'first_delivery_date','total_deliveries','customer_category']
                  ].drop_duplicates('customer_name')
        rows_cust = []
        for _, r in custs.iterrows():
            rows_cust.append((
                str(r['customer_name']),
                str(r['customer_type']),
                str(r['city']) if pd.notna(r['city']) else None,
                self._sf(r['first_delivery_date']),
                int(r['total_deliveries']),
                str(r['customer_category'])
            ))
        # dim_customer tiene muchos registros: insertar en lotes de 5000
        cur.execute("DELETE FROM dim_customer WHERE 1=1")
        batch = 5000
        for i in range(0, len(rows_cust), batch):
            cur.executemany("""
                INSERT INTO dim_customer (customer_name, customer_type, city,
                    first_delivery_date, total_deliveries, customer_category)
                VALUES (%s,%s,%s,%s,%s,%s)
            """, rows_cust[i:i+batch])
        logging.info(f"  dim_customer: {len(rows_cust):,} filas")

        self.sf_conn.commit()
        logging.info("✅ Todas las dimensiones cargadas (batch mode)")


    def load_trips_to_snowflake(self, df: pd.DataFrame):
        """
        Crea y carga staging_trips en Snowflake.

        JUSTIFICACION:
        Snowflake es una BD analitica (OLAP): no replica las tablas
        transaccionales de PostgreSQL. Sin embargo, la vista
        v_operations_deliveries necesita datos de trips para calcular
        KPIs como duracion real, entregas/hora y eficiencia por viaje.

        La tabla staging_trips en Snowflake actua como una copia
        desnormalizada y enriquecida de trips, optimizada para lecturas
        analiticas. Incluye campos derivados que en PostgreSQL no existen:
        trip_duration_hours, deliveries_in_trip, deliveries_per_hour.

        Se usa INSERT con subconsulta EXISTS para evitar duplicados
        en cargas incrementales sucesivas.
        """
        if not self.sf_conn:
            return

        logging.info("📤 Cargando staging_trips...")
        cur = self.sf_conn.cursor()

        cur.execute("""
            CREATE TABLE IF NOT EXISTS staging_trips (
                trip_id                INT          PRIMARY KEY,
                vehicle_id             INT          NOT NULL,
                driver_id              INT          NOT NULL,
                route_id               INT          NOT NULL,
                departure_datetime     TIMESTAMP_NTZ,
                arrival_datetime       TIMESTAMP_NTZ,
                fuel_consumed_liters   DECIMAL(10,2),
                total_weight_kg        DECIMAL(10,2),
                trip_status            VARCHAR(20),
                trip_duration_hours    DECIMAL(8,4),
                deliveries_in_trip     INT,
                deliveries_per_hour    DECIMAL(5,2),
                etl_batch_id           INT,
                etl_timestamp          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
            )
        """)

        trips_df = (
            df[[
                'trip_id','vehicle_id','driver_id','route_id',
                'departure_datetime','arrival_datetime',
                'fuel_consumed_liters','trip_total_weight_kg','trip_status',
                'trip_duration_hours','deliveries_in_trip','deliveries_per_hour'
            ]]
            .drop_duplicates('trip_id')
        )

        data = []
        for _, r in trips_df.iterrows():
            def safe_float(v):
                return float(v) if pd.notna(v) else None
            data.append((
                int(r['trip_id']),
                int(r['vehicle_id']),
                int(r['driver_id']),
                int(r['route_id']),
                self._sf(r['departure_datetime'], as_date=False),
                self._sf(r['arrival_datetime'], as_date=False),
                safe_float(r['fuel_consumed_liters']),
                safe_float(r['trip_total_weight_kg']),
                str(r['trip_status']),
                safe_float(r['trip_duration_hours']),
                int(r['deliveries_in_trip']),
                safe_float(r['deliveries_per_hour']),
                self.batch_id
            ))

        # MERGE para evitar duplicados en cargas incrementales
        cur.execute("DELETE FROM staging_trips WHERE 1=1")
        cur.executemany("""
            INSERT INTO staging_trips (
                trip_id, vehicle_id, driver_id, route_id,
                departure_datetime, arrival_datetime,
                fuel_consumed_liters, total_weight_kg, trip_status,
                trip_duration_hours, deliveries_in_trip, deliveries_per_hour,
                etl_batch_id
            ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """, data)

        self.sf_conn.commit()
        logging.info(f"  staging_trips: {len(data):,} registros")

    # ══════════════════════════════════════════
    # CARGA — fact_deliveries
    # ══════════════════════════════════════════

    def load_facts(self, df: pd.DataFrame):
        """
        Carga fact_deliveries usando write_pandas.
        Es el metodo oficial de Snowflake para cargas masivas:
        sube el DataFrame como CSV a un stage interno y ejecuta COPY INTO.
        400,000 filas en ~2-3 minutos.
        """
        if not self.sf_conn:
            df.to_csv('fact_deliveries_export.csv', index=False)
            logging.info("  CSV exportado: fact_deliveries_export.csv")
            return

        logging.info("📤 Cargando fact_deliveries con write_pandas...")
        from snowflake.connector.pandas_tools import write_pandas
        cur = self.sf_conn.cursor()

        # Obtener surrogated keys de las dimensiones ya cargadas
        cur.execute("SELECT vehicle_id, vehicle_key FROM dim_vehicle WHERE is_current=TRUE")
        veh_map = {r[0]: r[1] for r in cur.fetchall()}
        cur.execute("SELECT driver_id, driver_key FROM dim_driver WHERE is_current=TRUE")
        drv_map = {r[0]: r[1] for r in cur.fetchall()}
        cur.execute("SELECT route_id, route_key FROM dim_route")
        rte_map = {r[0]: r[1] for r in cur.fetchall()}
        cur.execute("SELECT customer_name, customer_key FROM dim_customer")
        cust_map = {r[0]: r[1] for r in cur.fetchall()}

        def safe(v):
            try:
                import math
                if math.isnan(float(v)): return None
            except (TypeError, ValueError):
                pass
            return v

        rows = []
        for _, r in df.iterrows():
            # Solo entregas con fecha de entrega real
            if pd.isna(r.get('delivered_datetime')):
                continue
            rows.append({
                'DATE_KEY':                     int(r['date_key']),
                'SCHEDULED_TIME_KEY':           int(r['scheduled_time_key']),
                'DELIVERED_TIME_KEY':           int(r['delivered_time_key']),
                'VEHICLE_KEY':                  veh_map.get(r['vehicle_id'],  int(r['vehicle_id'])),
                'DRIVER_KEY':                   drv_map.get(r['driver_id'],   int(r['driver_id'])),
                'ROUTE_KEY':                    rte_map.get(r['route_id'],    int(r['route_id'])),
                'CUSTOMER_KEY':                 cust_map.get(r['customer_name'], 1),
                'DELIVERY_ID':                  int(r['delivery_id']),
                'TRIP_ID':                      int(r['trip_id']),
                'TRACKING_NUMBER':              str(r['tracking_number']),
                'PACKAGE_WEIGHT_KG':            safe(r['package_weight_kg']),
                'DISTANCE_KM':                  float(r['distance_km']),
                'FUEL_CONSUMED_LITERS':         float(r['fuel_consumed_liters']),
                'DELIVERY_TIME_MINUTES':        safe(r['delivery_time_minutes']),
                'DELAY_MINUTES':                float(r['delay_minutes']),
                'DELIVERIES_PER_HOUR':          safe(r['deliveries_per_hour']),
                'FUEL_EFFICIENCY_KM_PER_LITER': safe(r['fuel_efficiency_km_per_liter']),
                'COST_PER_DELIVERY':            safe(r['cost_per_delivery']),
                'REVENUE_PER_DELIVERY':         float(r['revenue_per_delivery']),
                'IS_ON_TIME':                   bool(r['is_on_time']),
                'IS_DAMAGED':                   False,
                'RECIPIENT_SIGNATURE':          bool(r['recipient_signature']),
                'DELIVERY_STATUS':              str(r['delivery_status']),
                'DATA_QUALITY_FLAG':            str(r.get('data_quality_flag', 'ok')),
                'ETL_BATCH_ID':                 self.batch_id,
            })

        fact_df = pd.DataFrame(rows)
        cur.execute("DELETE FROM fact_deliveries WHERE 1=1")

        success, nchunks, nrows, _ = write_pandas(
            conn=self.sf_conn,
            df=fact_df,
            table_name='FACT_DELIVERIES',
            database='FLEETLOGIX_DW',
            schema='ANALYTICS',
            chunk_size=50_000,
            overwrite=False,
            quote_identifiers=False,
        )
        self.sf_conn.commit()
        self.metrics['records_loaded'] = nrows
        logging.info(f"✅ fact_deliveries: {nrows:,} registros ({nchunks} chunks)")


    def _calculate_daily_totals(self, df: pd.DataFrame):
        """Pre-calcula KPIs diarios con write_pandas."""
        if not self.sf_conn:
            return
        from snowflake.connector.pandas_tools import write_pandas

        cur = self.sf_conn.cursor()
        cur.execute("""
            CREATE TABLE IF NOT EXISTS daily_kpi_summary (
                summary_date DATE, etl_batch_id INT,
                total_deliveries INT, delivered_ok INT,
                pct_on_time DECIMAL(5,2), avg_delay_minutes DECIMAL(8,2),
                total_revenue_mxn DECIMAL(14,2), total_cost_mxn DECIMAL(14,2),
                avg_fuel_efficiency DECIMAL(8,4), total_km DECIMAL(12,2),
                total_fuel_liters DECIMAL(12,2),
                active_vehicles INT, active_drivers INT,
                created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
                PRIMARY KEY (summary_date, etl_batch_id)
            )
        """)
        cur.execute("DELETE FROM daily_kpi_summary WHERE 1=1")

        def sf(v):
            try:
                import math
                return None if math.isnan(float(v)) else round(float(v), 4)
            except: return None

        kpi_df = pd.DataFrame([{
            'SUMMARY_DATE':        str(date.today()),
            'ETL_BATCH_ID':        self.batch_id,
            'TOTAL_DELIVERIES':    len(df),
            'DELIVERED_OK':        int((df['delivery_status'] == 'delivered').sum()),
            'PCT_ON_TIME':         sf(df['is_on_time'].mean() * 100),
            'AVG_DELAY_MINUTES':   sf(df['delay_minutes'].mean()),
            'TOTAL_REVENUE_MXN':   sf(df['revenue_per_delivery'].sum()),
            'TOTAL_COST_MXN':      sf(df['cost_per_delivery'].fillna(0).sum()),
            'AVG_FUEL_EFFICIENCY': sf(df['fuel_efficiency_km_per_liter'].mean()),
            'TOTAL_KM':            sf(df['distance_km'].sum()),
            'TOTAL_FUEL_LITERS':   sf(df['fuel_consumed_liters'].sum()),
            'ACTIVE_VEHICLES':     int(df['vehicle_id'].nunique()),
            'ACTIVE_DRIVERS':      int(df['driver_id'].nunique()),
        }])

        write_pandas(
            conn=self.sf_conn,
            df=kpi_df,
            table_name='DAILY_KPI_SUMMARY',
            database='FLEETLOGIX_DW',
            schema='ANALYTICS',
            overwrite=False,
            quote_identifiers=False,
        )
        self.sf_conn.commit()
        logging.info(f"✅ daily_kpi_summary actualizado ({date.today()})")

---
## Parte 5 - Ejecucion del pipeline ETL

**Celda siguiente:** define `run_pipeline()`, funcion que ejecuta el ETL completo
y retorna el DataFrame transformado para explorarlo en el notebook.

**Celda de ejecucion:** llama `run_pipeline(full_history=True)` para cargar
el historico completo (403,874 filas) y muestra un preview de cada tabla del DW.

Los archivos CSV se generan en `./dw_data/` al terminar.

In [42]:
from datetime import date

def run_pipeline(full_history: bool = True):
    """
    Ejecuta el pipeline ETL completo E -> T -> L y retorna el DataFrame
    transformado para exploracion interactiva en el notebook.

    Parametros:
        full_history: True = todo el historico (primera carga)
                      False = solo el dia anterior (incremental diaria)
    """
    # Abrir conexion a PostgreSQL
    pg = psycopg2.connect(**PG_CONFIG)

    # ═══════════════════════════════════════════════════════════
    # FASE 1: EXTRACCION
    # ═══════════════════════════════════════════════════════════
    # DECISION DE DISENO: una sola query con 5 JOINs en lugar de
    # 5 queries separadas. Esto reduce los round-trips a la BD
    # de 5 a 1 y produce directamente el DataFrame unificado que
    # necesita la transformacion.
    # El script base tenia #TO DO# aqui — este es el completado.
    logging.info('FASE 1: EXTRACCION')

    if full_history:
        # PRIMERA CARGA: sin filtro de fechas, extrae todo el historico.
        # Cada fila del resultado = una entrega, con sus datos de viaje,
        # vehiculo, conductor y ruta ya incluidos (sin JOINs posteriores).
        query = '''
        SELECT
            -- Entrega individual
            d.delivery_id, d.trip_id, d.tracking_number,
            d.customer_name, d.delivery_address, d.package_weight_kg,
            d.scheduled_datetime, d.delivered_datetime,
            d.delivery_status, d.recipient_signature,
            -- Viaje que contiene la entrega
            t.departure_datetime, t.arrival_datetime,
            t.fuel_consumed_liters,
            t.total_weight_kg AS trip_total_weight_kg,
            t.status          AS trip_status,
            -- Vehiculo asignado al viaje
            v.vehicle_id, v.license_plate, v.vehicle_type, v.capacity_kg,
            v.fuel_type, v.acquisition_date, v.status AS vehicle_status,
            -- Conductor asignado al viaje
            dr.driver_id, dr.employee_code, dr.first_name, dr.last_name,
            dr.license_number, dr.license_expiry, dr.phone, dr.hire_date,
            dr.status AS driver_status,
            -- Ruta seguida
            r.route_id, r.route_code, r.origin_city, r.destination_city,
            r.distance_km, r.estimated_duration_hours, r.toll_cost
        FROM deliveries d
        JOIN trips    t  ON d.trip_id    = t.trip_id
        JOIN vehicles v  ON t.vehicle_id = v.vehicle_id
        JOIN drivers  dr ON t.driver_id  = dr.driver_id
        JOIN routes   r  ON t.route_id   = r.route_id
        WHERE t.status = 'completed'            -- Solo viajes terminados
          AND t.arrival_datetime IS NOT NULL     -- Con hora de llegada
          AND t.fuel_consumed_liters IS NOT NULL -- Con combustible registrado
        ORDER BY d.delivery_id
        '''
    else:
        # CARGA INCREMENTAL: solo el dia anterior.
        # El pipeline nocturno usa este modo para mantener el DW al dia.
        ayer = (datetime.now() - timedelta(days=1)).date()
        hoy  = datetime.now().date()
        query = f'''
        SELECT d.delivery_id, d.trip_id, d.tracking_number,
               d.customer_name, d.delivery_address, d.package_weight_kg,
               d.scheduled_datetime, d.delivered_datetime,
               d.delivery_status, d.recipient_signature,
               t.departure_datetime, t.arrival_datetime,
               t.fuel_consumed_liters,
               t.total_weight_kg AS trip_total_weight_kg,
               t.status AS trip_status,
               v.vehicle_id, v.license_plate, v.vehicle_type, v.capacity_kg,
               v.fuel_type, v.acquisition_date, v.status AS vehicle_status,
               dr.driver_id, dr.employee_code, dr.first_name, dr.last_name,
               dr.license_number, dr.license_expiry, dr.phone, dr.hire_date,
               dr.status AS driver_status,
               r.route_id, r.route_code, r.origin_city, r.destination_city,
               r.distance_km, r.estimated_duration_hours, r.toll_cost
        FROM deliveries d
        JOIN trips    t  ON d.trip_id    = t.trip_id
        JOIN vehicles v  ON t.vehicle_id = v.vehicle_id
        JOIN drivers  dr ON t.driver_id  = dr.driver_id
        JOIN routes   r  ON t.route_id   = r.route_id
        WHERE d.scheduled_datetime >= \'{ayer}\'
          AND d.scheduled_datetime  < \'{hoy}\'
          AND t.status = 'completed'
          AND t.arrival_datetime IS NOT NULL
          AND t.fuel_consumed_liters IS NOT NULL
        ORDER BY d.delivery_id
        '''

    # pd.read_sql ejecuta el SQL y retorna DataFrame con nombres de columna
    # tomados automaticamente de los alias del SELECT
    df = pd.read_sql(query, pg)
    logging.info(f'  Extraidos: {len(df):,} registros')

    # ═══════════════════════════════════════════════════════════
    # FASE 2: TRANSFORMACION
    # ═══════════════════════════════════════════════════════════
    # Genera todos los campos derivados que el esquema de Snowflake
    # requiere pero que NO existen en PostgreSQL.
    logging.info('FASE 2: TRANSFORMACION')
    today = pd.Timestamp.now().normalize()

    # Convertir columnas de texto a tipo datetime.
    # errors='coerce' convierte valores invalidos a NaT en lugar de error.
    for col in ['scheduled_datetime','delivered_datetime','departure_datetime',
                'arrival_datetime','hire_date','acquisition_date','license_expiry']:
        df[col] = pd.to_datetime(df[col], errors='coerce')

    # ── CAMPOS PARA dim_driver ────────────────────────────────
    # full_name: PostgreSQL guarda first_name y last_name separados.
    # Snowflake espera full_name en dim_driver.
    df['full_name'] = df['first_name'].str.strip() + ' ' + df['last_name'].str.strip()

    # experience_months: antiguedad del conductor en meses.
    # .clip(lower=0) evita valores negativos si hire_date esta en el futuro.
    # .fillna(0) maneja conductores sin fecha de contratacion registrada.
    df['experience_months'] = (
        (today - df['hire_date']).dt.days // 30
    ).clip(lower=0).fillna(0).astype(int)

    # ── CAMPOS PARA dim_vehicle ───────────────────────────────
    # age_months: antiguedad del vehiculo en meses desde su compra.
    df['age_months'] = (
        (today - df['acquisition_date']).dt.days // 30
    ).clip(lower=0).fillna(0).astype(int)

    # last_maintenance_date: requiere consulta adicional a la tabla
    # maintenance (no esta en el DataFrame principal).
    ultimo_mant = pd.read_sql(
        'SELECT vehicle_id, MAX(maintenance_date)::DATE AS lmd '
        'FROM maintenance GROUP BY vehicle_id', pg
    ).set_index('vehicle_id')['lmd'].to_dict()
    df['last_maintenance_date'] = df['vehicle_id'].map(ultimo_mant)

    # ── CAMPOS PARA dim_route ─────────────────────────────────
    # difficulty_level: clasifica la ruta por su longitud.
    # Permite agrupar rutas en queries sin calcular rangos cada vez.
    def dificultad(km):
        if pd.isna(km): return 'Desconocido'
        return 'Facil' if km < 200 else ('Medio' if km <= 800 else 'Dificil')
    df['difficulty_level'] = df['distance_km'].apply(dificultad)

    # route_type: Urbana si la ruta no cruza ciudades (entrega de ultima milla).
    df['route_type'] = np.where(
        df['origin_city'] == df['destination_city'], 'Urbana', 'Interurbana')

    # ── CAMPOS PARA dim_customer ──────────────────────────────
    # PostgreSQL no tiene tabla 'customers'. Los clientes se derivan de deliveries.
    # city: tomamos el ultimo segmento de delivery_address (tras la ultima coma).
    df['city'] = df['delivery_address'].str.split(',').str[-1].str.strip()

    # customer_type: heuristica — empresas mexicanas incluyen SA, SA de CV, SRL.
    df['customer_type'] = np.where(
        df['customer_name'].str.contains(
            r'(?:SA|SRL|SC|S\.A)', case=False, na=False, regex=True),
        'Empresa', 'Individual')

    # first_delivery_date: fecha minima de entrega por cliente en el batch.
    # .transform('min') asigna el minimo de grupo a cada fila del mismo cliente.
    df['first_delivery_date'] = pd.to_datetime(
        df.groupby('customer_name')['scheduled_datetime'].transform('min')).dt.strftime('%Y-%m-%d')

    # total_deliveries: conteo de entregas del cliente en el batch actual.
    df['total_deliveries'] = df.groupby('customer_name')['delivery_id'].transform('count')

    # customer_category: segmentacion por volumen de entregas.
    df['customer_category'] = pd.cut(
        df['total_deliveries'],
        bins=[0, 2, 10, float('inf')],
        labels=['Ocasional', 'Regular', 'Premium'], right=True
    ).astype(str)

    # ── METRICAS PARA fact_deliveries ─────────────────────────
    # delivery_time_minutes: diferencia entre entrega real y programada.
    # PUEDE SER NEGATIVO (entrega anticipada). Se CONSERVA y se marca en
    # data_quality_flag. El script original los eliminaba incorrectamente.
    df['delivery_time_minutes'] = (
        (df['delivered_datetime'] - df['scheduled_datetime'])
        .dt.total_seconds() / 60
    ).round(2)

    # delay_minutes: solo el exceso (parte positiva del tiempo de entrega).
    # .clip(lower=0) convierte negativos en 0 (no hay retraso negativo).
    df['delay_minutes'] = df['delivery_time_minutes'].clip(lower=0)

    # is_on_time: True si el retraso esta dentro del umbral de tolerancia.
    df['is_on_time'] = df['delay_minutes'] <= ON_TIME_THRESHOLD

    # trip_duration_hours: duracion total del viaje en horas.
    df['trip_duration_hours'] = (
        (df['arrival_datetime'] - df['departure_datetime'])
        .dt.total_seconds() / 3600
    ).round(4)

    # deliveries_in_trip: cuantas entregas comparte este viaje.
    # Necesario para calcular el combustible proporcional por entrega.
    df['deliveries_in_trip'] = df.groupby('trip_id')['delivery_id'].transform('count')

    # deliveries_per_hour: productividad del viaje.
    # .replace(0, np.nan) evita division por cero.
    df['deliveries_per_hour'] = (
        df['deliveries_in_trip'] / df['trip_duration_hours'].replace(0, np.nan)
    ).round(2)

    # fuel_efficiency_km_per_liter: km por litro (mayor = mas eficiente).
    df['fuel_efficiency_km_per_liter'] = (
        df['distance_km'] / df['fuel_consumed_liters'].replace(0, np.nan)
    ).round(2)

    # cost_per_delivery: (litros * precio + peaje) / numero de entregas del viaje.
    # Distribuye el costo del viaje proporcionalmente entre sus entregas.
    df['cost_per_delivery'] = (
        (df['fuel_consumed_liters'] * PRECIO_LITRO_MXN + df['toll_cost'])
        / df['deliveries_in_trip']
    ).round(2)

    # revenue_per_delivery: ingreso base + tarifa variable por peso del paquete.
    df['revenue_per_delivery'] = (
        REVENUE_BASE_MXN + df['package_weight_kg'] * REVENUE_KG_MXN
    ).round(2)

    # ── CLAVES PARA EL MODELO DIMENSIONAL ────────────────────
    # date_key: formato YYYYMMDD como entero (ej: 20240315 para el 15-mar-2024).
    # Este formato es el estandar Kimball: permite ordenar sin convertir tipos.
    df['date_key'] = df['scheduled_datetime'].dt.strftime('%Y%m%d').astype(int)

    # scheduled_time_key y delivered_time_key: formato HHMM (ej: 830 para 08:30).
    df['scheduled_time_key'] = (
        df['scheduled_datetime'].dt.hour * 100 + df['scheduled_datetime'].dt.minute)
    df['delivered_time_key'] = np.where(
        df['delivered_datetime'].notna(),
        df['delivered_datetime'].dt.hour * 100 + df['delivered_datetime'].dt.minute,
        df['scheduled_time_key']  # Fallback si no hay hora de entrega
    ).astype(int)

    # ── SCD TIPO 2 ────────────────────────────────────────────
    # Slowly Changing Dimensions: conservan el historial de cambios.
    # valid_from / valid_to definen el rango de vigencia del registro.
    df['valid_from'] = df['scheduled_datetime'].dt.strftime('%Y-%m-%d')

    # CORRECCION DEL ERROR EN LINEA 145 DEL SCRIPT ORIGINAL:
    # pd.to_datetime('9999-12-31') genera OverflowError en numpy < 2.0
    # porque intenta convertirlo a nanosegundos int64 (limite: anio ~2262).
    # La correccion: date() de Python puro no tiene ese limite.
    df['valid_to']   = date(9999, 12, 31)  # FIX del OverflowError
    df['is_current'] = True

    # performance_category del conductor: basado en tasa de puntualidad.
    # Alto >60% / Medio 40-60% / Bajo <40% de entregas a tiempo.
    tasa_ot = df.groupby('driver_id')['is_on_time'].transform('mean')
    df['performance_category'] = pd.cut(
        tasa_ot,
        bins=[-0.001, 0.40, 0.60, 1.001],
        labels=['Bajo', 'Medio', 'Alto']
    ).astype(str)

    # ── CONTROL DE CALIDAD: MARCA, NO ELIMINA ────────────────
    # CORRECCION del script original: las validaciones eliminaban filas.
    # Una entrega anticipada (tiempo negativo) puede ser VALIDA.
    # La correccion conserva TODOS los registros y agrega data_quality_flag
    # para que el analista decida si excluirlos con WHERE flag='ok'.
    flags = pd.Series('', index=df.index)
    # Flag: peso fuera del rango valido (0 a 9,999 kg)
    mask = (df['package_weight_kg'] <= 0) | (df['package_weight_kg'] > 9999)
    flags[mask] = 'peso_invalido'
    # Flag: mas de 24h anticipada = probable error de datos
    mask2 = df['delivery_time_minutes'].notna() & (df['delivery_time_minutes'] < -1440)
    flags[mask2] = flags[mask2].where(flags[mask2]=='', flags[mask2]+'|')+'tiempo_muy_negativo'
    # Flag: viaje de mas de 72 horas = probable error
    mask3 = df['trip_duration_hours'].notna() & (df['trip_duration_hours'] > MAX_TRIP_HOURS)
    flags[mask3] = flags[mask3].where(flags[mask3]=='', flags[mask3]+'|')+'viaje_muy_largo'
    df['data_quality_flag'] = flags.str.strip('|').replace('', 'ok')

    n_marcados = (df['data_quality_flag'] != 'ok').sum()
    logging.info(f'  Transformados: {len(df):,} filas | Marcadas: {n_marcados:,}')

    # ═══════════════════════════════════════════════════════════
    # FASE 3: CARGA
    # ═══════════════════════════════════════════════════════════
    # Usa la clase FleetLogixETL para cargar cada tabla en Snowflake.
    # Las dimensiones se cargan PRIMERO porque fact_deliveries necesita
    # sus surrogated keys (vehicle_key, driver_key, etc.).
    logging.info('FASE 3: CARGA')
    etl = FleetLogixETL()
    etl.pg_conn = pg
    etl.sf_conn = None

    if SNOWFLAKE_ENABLED:
        try:
            import snowflake.connector
            etl.sf_conn = snowflake.connector.connect(**SNOWFLAKE_CONFIG)
        except Exception as e:
            logging.warning(f'Snowflake no disponible, modo CSV: {e}')

    # Orden de carga (respeta dependencias de claves foraneas):
    etl.load_dimensions(df)           # 1. dim_date, dim_time, dim_vehicle,
                                       #    dim_driver, dim_route, dim_customer
    etl.load_trips_to_snowflake(df)   # 2. staging_trips (nueva tabla)
    etl.load_facts(df)                # 3. fact_deliveries (tabla de hechos)
    etl._calculate_daily_totals(df)   # 4. daily_kpi_summary (resumen)

    if etl.sf_conn: etl.sf_conn.close()
    pg.close()
    logging.info('PIPELINE COMPLETADO')
    return df


print('Funcion run_pipeline() definida.')
print('Ejecuta la siguiente celda para correr el pipeline completo.')

Funcion run_pipeline() definida.
Ejecuta la siguiente celda para correr el pipeline completo.

In [43]:
# Ejecutar el pipeline completo
# full_history=True: primera carga — extrae todo el historico de PostgreSQL
# full_history=False: carga incremental — solo el dia anterior
print('Iniciando pipeline ETL...')
print('Primera vez puede tardar 3-5 minutos (403,874 filas)')
print()

df_etl = run_pipeline(full_history=True)

# ── Reporte de resultados ─────────────────────────────────────
print()
print('RESUMEN DEL PIPELINE ETL')
print('=' * 55)
print(f'  Registros extraidos    : {len(df_etl):,}')
print(f'  Registros transformados: {len(df_etl):,}  (0 eliminados)')
print(f'  Registros con flag     : {(df_etl["data_quality_flag"]!="ok").sum():,}')
print(f'  Correccion OverflowError valid_to = {df_etl["valid_to"].iloc[0]}')
print()

# ── Preview de cada tabla del DW ──────────────────────────────
# Muestra las primeras 3 filas de cada tabla para verificar la estructura
tablas_preview = {
    'dim_date': (
        df_etl[['date_key']].drop_duplicates()
        .assign(year=lambda d: d['date_key']//10000,
                month=lambda d: (d['date_key']//100)%100)
    ),
    'dim_vehicle': df_etl[[
        'vehicle_id','license_plate','vehicle_type',
        'age_months','last_maintenance_date','vehicle_status'
    ]].drop_duplicates('vehicle_id'),
    'dim_driver': df_etl[[
        'driver_id','full_name','experience_months',
        'performance_category','driver_status'
    ]].drop_duplicates('driver_id'),
    'dim_route': df_etl[[
        'route_id','route_code','origin_city','destination_city',
        'difficulty_level','route_type'
    ]].drop_duplicates('route_id'),
    'dim_customer': df_etl[[
        'customer_name','customer_type','city','customer_category'
    ]].drop_duplicates('customer_name'),
    'staging_trips': df_etl[[
        'trip_id','trip_duration_hours','deliveries_in_trip',
        'deliveries_per_hour','trip_status'
    ]].drop_duplicates('trip_id'),
    'fact_deliveries': df_etl[
        df_etl['delivered_datetime'].notna()
    ][['delivery_id','date_key','delay_minutes','is_on_time',
       'cost_per_delivery','revenue_per_delivery','data_quality_flag']],
}

print('TABLAS DEL DATA WAREHOUSE')
print('-' * 55)
for nombre, tabla in tablas_preview.items():
    tipo = 'HECHOS    ' if nombre == 'fact_deliveries' else 'Dimension '
    print(f'\n[{tipo}] {nombre}  ->  {len(tabla):,} registros')
    display(tabla.head(3))

2026-06-08 23:00:37,798  INFO  FASE 1: EXTRACCION

Iniciando pipeline ETL...
Primera vez puede tardar 3-5 minutos (403,874 filas)

C:\Users\Ejecutivo-07\AppData\Local\Temp\ipykernel_22164\3684518866.py:97: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, pg)
2026-06-08 23:01:08,086  INFO    Extraidos: 400,000 registros
2026-06-08 23:01:08,089  INFO  FASE 2: TRANSFORMACION
C:\Users\Ejecutivo-07\AppData\Local\Temp\ipykernel_22164\3684518866.py:134: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ultimo_mant = pd.read_sql(
2026-06-08 23:01:19,574  INFO    Transformados: 400,000 filas | Marcadas: 0
2026-06-08 23:01:19,575  INFO  FASE 3: CARGA
2026-06-08 23:01:19,608  INFO  Snowflake Connector for Python Version: 4.6.0, Python Version: 3.14.3, Platform: Windows-10-10.0.19045-SP0
2026-06-08 23:01:19,624  INFO  Connecting to GLOBAL Snowflake domain
2026-06-08 23:01:23,477  INFO  📤 Cargando dimensiones en Snowflake (modo batch)...
C:\Users\Ejecutivo-07\AppData\Local\Temp\ipykernel_22164\836357867.py:500: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ultimo_mant = pd.read_sql(
2026-06-08 23:01:26,813  INFO    dim_date: 697 filas
2026-06-08 23:01:29,315  INFO    dim_time: 1,440 filas
2026-06-08 23:01:31,855  INFO    dim_vehicle: 182 filas
2026-06-08 23:01:33,695  INFO    dim_driver: 378 filas
2026-06-08 23:01:35,243  INFO    dim_route: 48 filas
2026-06-08 23:07:13,441  INFO    dim_customer: 383,047 filas
2026-06-08 23:07:13,827  INFO  ✅ Todas las dimensiones cargadas (batch mode)
2026-06-08 23:07:13,998  INFO  📤 Cargando staging_trips...
2026-06-08 23:09:58,276  INFO    staging_trips: 99,950 registros
2026-06-08 23:09:58,391  INFO  📤 Cargando fact_deliveries con write_pandas...
2026-06-08 23:12:14,789  INFO  ✅ fact_deliveries: 400,000 registros (8 chunks)
2026-06-08 23:12:27,684  INFO  ✅ daily_kpi_summary actualizado (2026-06-08)
2026-06-08 23:12:28,065  INFO  PIPELINE COMPLETADO

RESUMEN DEL PIPELINE ETL
=======================================================
  Registros extraidos    : 400,000
  Registros transformados: 400,000  (0 eliminados)
  Registros con flag     : 0
  Correccion OverflowError valid_to = 9999-12-31

TABLAS DEL DATA WAREHOUSE
-------------------------------------------------------

[Dimension ] dim_date  ->  697 registros

    date_key  year  month
0   20240603  2024      6
5   20240604  2024      6
34  20240605  2024      6

[Dimension ] dim_vehicle  ->  182 registros

,vehicle_id,license_plate,vehicle_type,age_months,last_maintenance_date,vehicle_status
0,48,ATK-172,Camión Grande,10,2026-04-03,active
4,96,KYC-995,Camión Mediano,60,2026-04-03,active
8,196,HEP-603,Camión Grande,49,2026-03-31,active

[Dimension ] dim_driver  ->  378 registros

,driver_id,full_name,experience_months,performance_category,driver_status
0,59,Ricardo Quintero Pineda,16,Alto,active
4,147,María José Medina Leyva,12,Alto,active
8,123,Daniela Menéndez Rodríquez,31,Alto,active

[Dimension ] dim_route  ->  48 registros

,route_id,route_code,origin_city,destination_city,difficulty_level,route_type
0,7,R007,Ciudad de México,Puebla,Facil,Interurbana
4,26,R026,Monterrey,Guadalajara,Medio,Interurbana
8,20,R020,Guadalajara,Tijuana,Dificil,Interurbana

[Dimension ] dim_customer  ->  383,047 registros

,customer_name,customer_type,city,customer_category
0,César Luis Piña,Empresa,Puebla,Ocasional
1,Rosalia Carolina Quintana Armendáriz,Empresa,Puebla,Ocasional
2,Iván Mauricio Rodríguez,Individual,Puebla,Ocasional

[Dimension ] staging_trips  ->  99,950 registros

,trip_id,trip_duration_hours,deliveries_in_trip,deliveries_per_hour,trip_status
0,1,1.7052,4,2.35,completed
4,2,11.4240,4,0.35,completed
8,3,35.4133,2,0.06,completed

[HECHOS    ] fact_deliveries  ->  400,000 registros

,delivery_id,date_key,delay_minutes,is_on_time,cost_per_delivery,revenue_per_delivery,data_quality_flag
0,1,20240603,114.0,False,121.44,1442.45,ok
1,2,20240603,0.0,True,121.44,866.93,ok
2,3,20240603,0.0,True,121.44,1316.98,ok

---
## Parte 6 - Telemetria IoT en MongoDB

### Por que MongoDB y no PostgreSQL para IoT

Los sensores vehiculares generan datos **heterogeneos**: un camion reporta GPS,
temperatura de motor, presion de llantas y alertas, mientras que una motocicleta
solo reporta GPS y velocidad.

**PostgreSQL** necesitaria columnas NULL o tablas separadas por tipo de sensor.
**MongoDB** almacena documentos JSON con campos diferentes por vehiculo,
sin esquema fijo (schema-less). Ideal para datos variables e irregulares.

### Estructura de un documento IoT

```json
{
  "vehicle_id": 42,
  "trip_id": 8731,
  "timestamp": "2024-03-15T14:32:01",
  "location": { "lat": 19.4326, "lon": -99.1332, "city": "Ciudad de Mexico" },
  "speed_kmh": 65.3,
  "fuel_level_pct": 72.1,
  "engine_temp_c": 91.5,
  "driver_behavior": { "score": 85, "harsh_braking": false },
  "events": [],
  "alerts": []
}
```

Los `vehicle_id` y `trip_id` son los mismos de PostgreSQL para cruzar datos.

In [32]:
# Coordenadas de las 5 ciudades de operacion de FleetLogix
COORDENADAS = {
    'Ciudad de Mexico': (19.4326, -99.1332),
    'Guadalajara':      (20.6597, -103.3496),
    'Monterrey':        (25.6866, -100.3161),
    'Puebla':           (19.0414, -98.2063),
    'Tijuana':          (32.5149, -117.0382),
}

# Eventos posibles con su probabilidad de ocurrencia.
# El 70% de lecturas son normales; el resto son eventos de riesgo.
EVENTOS = [
    ('normal',           0.70),  # Conduccion sin incidentes
    ('harsh_braking',    0.10),  # Frenada brusca
    ('speeding',         0.08),  # Exceso de velocidad
    ('sharp_turn',       0.06),  # Giro brusco
    ('idle_too_long',    0.04),  # Motor en ralenti mucho tiempo
    ('low_fuel_warning', 0.02),  # Combustible bajo
]
# Penalizacion al score de conduccion por tipo de evento
PENALIZ = {'normal':0, 'harsh_braking':-15, 'speeding':-12,
           'sharp_turn':-8, 'idle_too_long':-3, 'low_fuel_warning':-2}

# Usar IDs reales del ETL para coherencia entre PostgreSQL y MongoDB
ids_vehiculos = df_etl['vehicle_id'].unique().tolist()
ids_viajes    = df_etl['trip_id'].unique().tolist()

# Generar 10,000 documentos IoT
# Cada documento = una lectura de sensores cada ~5 minutos
docs_iot = []
inicio   = datetime.now() - timedelta(days=30)

for i in tqdm(range(10_000), desc='Generando telemetria IoT'):
    ciudad   = random.choice(list(COORDENADAS.keys()))
    lat, lon = COORDENADAS[ciudad]
    ts       = inicio + timedelta(minutes=i*5 + random.randint(-2,2))

    # Velocidad con distribucion realista (no uniforme)
    velocidad = max(0, float(
        np.random.choice([0, 30, 45, 60, 80, 100, 110],
                         p=[0.05, 0.15, 0.20, 0.25, 0.20, 0.10, 0.05])
        + random.gauss(0, 5)
    ))

    # Seleccionar evento segun probabilidades
    evento = random.choices(
        [e[0] for e in EVENTOS],
        weights=[e[1] for e in EVENTOS]
    )[0]

    # Score: base 85 con variacion y penalizacion por evento
    score = max(0, min(100, 85 + random.randint(-5,10) + PENALIZ[evento]))

    docs_iot.append({
        'vehicle_id': int(random.choice(ids_vehiculos)),
        'trip_id':    int(random.choice(ids_viajes)),
        'timestamp':  ts.isoformat(),
        'location': {
            'lat':  round(lat + random.gauss(0, 0.05), 6),
            'lon':  round(lon + random.gauss(0, 0.05), 6),
            'city': ciudad
        },
        'speed_kmh':      round(velocidad, 1),
        # Nivel de combustible decrece gradualmente con variacion gaussiana
        'fuel_level_pct': round(max(5, 90-(i%200)*0.3+random.gauss(0,2)), 1),
        'engine_temp_c':  round(random.uniform(85,98)+(i%100)*0.02, 1),
        'driver_behavior': {
            'score':         score,
            'harsh_braking': evento == 'harsh_braking',
            'speeding':      evento == 'speeding',
            'sharp_turn':    evento == 'sharp_turn'
        },
        # Lista de eventos activos (vacia si es conduccion normal)
        'events': [evento] if evento != 'normal' else [],
        # Alertas que requieren atencion inmediata del operador
        'alerts': [evento] if evento in ['low_fuel_warning','harsh_braking'] else []
    })

# Guardar muestra de 100 documentos como JSON local
with open(f'{OUTPUT_FOLDER}/vehicle_telemetry_sample.json','w') as f:
    json.dump(docs_iot[:100], f, indent=2, ensure_ascii=False, default=str)

# Insertar en MongoDB si esta habilitado
if MONGODB_ENABLED:
    from pymongo import MongoClient
    db  = MongoClient(MONGODB_URI)['fleetlogix_iot']
    col = db['vehicle_telemetry']
    # Indices para acelerar las queries mas comunes
    col.create_index('vehicle_id')
    col.create_index('trip_id')
    col.create_index([('location.city',1),('timestamp',-1)])
    for i in range(0, len(docs_iot), 1000):
        col.insert_many(docs_iot[i:i+1000])
    print(f'MongoDB: {len(docs_iot):,} documentos insertados')
else:
    print(f'Muestra guardada: {OUTPUT_FOLDER}/vehicle_telemetry_sample.json')

# Convertir a DataFrame para analisis local
df_iot = pd.DataFrame([{
    'vehicle_id':    d['vehicle_id'],
    'city':          d['location']['city'],
    'speed_kmh':     d['speed_kmh'],
    'score':         d['driver_behavior']['score'],
    'harsh_braking': d['driver_behavior']['harsh_braking'],
    'speeding':      d['driver_behavior']['speeding'],
    'has_alert':     len(d['alerts']) > 0
} for d in docs_iot])

print(f'Telemetria IoT generada:')
print(f'  Total documentos    : {len(docs_iot):,}')
print(f'  Frenadas bruscas    : {df_iot["harsh_braking"].sum():,}  ({df_iot["harsh_braking"].mean()*100:.1f}%)')
print(f'  Excesos velocidad   : {df_iot["speeding"].sum():,}  ({df_iot["speeding"].mean()*100:.1f}%)')
print(f'  Score prom conduccion: {df_iot["score"].mean():.1f}/100')

Generando telemetria IoT: 100%|██████████| 10000/10000 [00:00<00:00, 12697.16it/s]

Muestra guardada: ./dw_data/vehicle_telemetry_sample.json
Telemetria IoT generada:
  Total documentos    : 10,000
  Frenadas bruscas    : 988  (9.9%)
  Excesos velocidad   : 795  (8.0%)
  Score prom conduccion: 84.4/100

---
## Parte 7 - Consultas analiticas sobre el Data Warehouse

Estas queries demuestran el valor del modelo estrella: responden preguntas
de negocio complejas con operaciones simples sobre el DW, sin los JOINs y
calculos adicionales que requeririan en PostgreSQL.

En Snowflake se ejecutarian con SQL. Aqui las replicamos en pandas sobre
el DataFrame del ETL para mostrar los mismos resultados.

In [33]:
# DW-Q1: Entregas por trimestre y KPIs de puntualidad
# En Snowflake:
#   SELECT d.year, d.quarter, COUNT(*), AVG(f.delay_minutes), SUM(f.revenue_per_delivery)
#   FROM fact_deliveries f JOIN dim_date d ON f.date_key = d.date_key
#   GROUP BY d.year, d.quarter
print('DW-Q1: Entregas por trimestre')
print('-' * 55)
fact = df_etl[df_etl['delivered_datetime'].notna()].copy()
fact['year']    = pd.to_datetime(fact['scheduled_datetime']).dt.year
fact['quarter'] = pd.to_datetime(fact['scheduled_datetime']).dt.quarter

q1 = (fact.groupby(['year','quarter']).agg(
    total_entregas   = ('delivery_id', 'count'),
    pct_on_time      = ('is_on_time', 'mean'),
    delay_prom_min   = ('delay_minutes', 'mean'),
    revenue_total    = ('revenue_per_delivery', 'sum'),
    costo_total      = ('cost_per_delivery', 'sum'),
).reset_index())
q1['pct_on_time']    = (q1['pct_on_time'] * 100).round(1)
q1['delay_prom_min'] = q1['delay_prom_min'].round(1)
q1['revenue_total']  = q1['revenue_total'].round(0)
q1['periodo']        = q1['year'].astype(str) + '-Q' + q1['quarter'].astype(str)
display(q1[['periodo','total_entregas','pct_on_time','delay_prom_min',
            'revenue_total','costo_total']].sort_values('periodo'))

DW-Q1: Entregas por trimestre
-------------------------------------------------------

,periodo,total_entregas,pct_on_time,delay_prom_min,revenue_total,costo_total
0,2024-Q2,15780,90.4,18.2,11553933.0,23435378.59
1,2024-Q3,53183,90.2,18.6,38621234.0,78874430.74
2,2024-Q4,52931,90.3,18.6,38724993.0,77626997.11
3,2025-Q1,51817,90.2,18.6,38050946.0,77720415.70
4,2025-Q2,52435,90.2,18.7,37809514.0,78066659.07
5,2025-Q3,52997,90.0,19.0,38374066.0,78243203.09
6,2025-Q4,53022,89.8,19.0,38363588.0,78548365.26
7,2026-Q1,51900,90.1,18.8,37781926.0,77333137.33
8,2026-Q2,15935,90.3,18.5,11736878.0,23573923.97

In [34]:
# DW-Q2: Eficiencia operativa por tipo de vehiculo
# vehicle_type ya esta en df_etl (viene del JOIN con vehicles en la extraccion).
# No es necesario volver a mergear dim_vehicle — el campo existe directamente.
print('DW-Q2: Eficiencia por tipo de vehiculo')
print('-' * 55)
q2 = (fact
    .groupby('vehicle_type').agg(
        flota         = ('vehicle_id', 'nunique'),
        entregas      = ('delivery_id', 'count'),
        pct_on_time   = ('is_on_time', 'mean'),
        eff_km_l      = ('fuel_efficiency_km_per_liter', 'mean'),
        costo_prom    = ('cost_per_delivery', 'mean'),
        revenue_prom  = ('revenue_per_delivery', 'mean'),
    ).reset_index())
q2['pct_on_time']  = (q2['pct_on_time'] * 100).round(1)
q2['eff_km_l']     = q2['eff_km_l'].round(2)
q2['costo_prom']   = q2['costo_prom'].round(2)
display(q2)

DW-Q2: Eficiencia por tipo de vehiculo
-------------------------------------------------------

,vehicle_type,flota,entregas,pct_on_time,eff_km_l,costo_prom,revenue_prom
0,Camión Grande,55,121163,90.2,8.98,1479.36,1211.768550
1,Camión Mediano,55,121820,90.2,8.98,1488.75,758.780834
2,Motocicleta,22,47132,89.9,8.97,1478.97,91.651728
3,Van,50,109885,90.2,8.98,1484.40,431.734569

In [35]:
# DW-Q3: Performance de rutas por nivel de dificultad
# difficulty_level y route_type ya estan en df_etl (calculados en transform_data).
print('DW-Q3: Rutas por nivel de dificultad')
print('-' * 55)
q3 = (fact
    .groupby('difficulty_level').agg(
        num_rutas   = ('route_id', 'nunique'),
        entregas    = ('delivery_id', 'count'),
        pct_on_time = ('is_on_time', 'mean'),
        eff_km_l    = ('fuel_efficiency_km_per_liter', 'mean'),
        delay_prom  = ('delay_minutes', 'mean'),
    ).reset_index())
q3['pct_on_time'] = (q3['pct_on_time'] * 100).round(1)
q3['eff_km_l']    = q3['eff_km_l'].round(2)
q3['delay_prom']  = q3['delay_prom'].round(1)
display(q3)

DW-Q3: Rutas por nivel de dificultad
-------------------------------------------------------

  difficulty_level  num_rutas  entregas  pct_on_time  eff_km_l  delay_prom
0          Dificil         29    242017         90.2      8.98        18.7
1            Facil          6     50416         90.3      8.99        18.6
2            Medio         13    107567         90.0      8.96        18.9

In [36]:
# DW-Q4: Distribucion de entregas por turno horario
# Usa dim_time: la dimension de tiempo permite agrupar por turno
# sin calcular rangos de hora en cada query.
print('DW-Q4: Entregas por turno horario')
print('-' * 55)
def turno(h):
    if   h < 6:  return 'Madrugada (00-06h)'
    elif h < 14: return 'Turno 1   (06-14h)'
    elif h < 22: return 'Turno 2   (14-22h)'
    else:        return 'Turno 3   (22-24h)'

fact['turno'] = pd.to_datetime(fact['scheduled_datetime']).dt.hour.apply(turno)
q4 = (fact.groupby('turno').agg(
    entregas    = ('delivery_id', 'count'),
    pct_on_time = ('is_on_time', 'mean'),
    delay_prom  = ('delay_minutes', 'mean'),
).reset_index().sort_values('entregas', ascending=False))
q4['pct_on_time'] = (q4['pct_on_time'] * 100).round(1)
q4['delay_prom']  = q4['delay_prom'].round(1)
display(q4)

DW-Q4: Entregas por turno horario
-------------------------------------------------------

                turno  entregas  pct_on_time  delay_prom
2  Turno 2   (14-22h)    162502         90.2        18.6
1  Turno 1   (06-14h)    125620         90.0        18.9
0  Madrugada (00-06h)     78216         90.2        18.7
3  Turno 3   (22-24h)     33662         90.2        18.5

In [37]:
# IoT-Q1: Vehiculos con mas frenadas bruscas (riesgo de accidente)
print('IoT-Q1: Top 10 vehiculos con mas frenadas bruscas')
print('-' * 55)
display(
    df_iot[df_iot['harsh_braking']]
    .groupby('vehicle_id').size()
    .sort_values(ascending=False).head(10)
    .reset_index().rename(columns={0:'frenadas_bruscas'})
)

# IoT-Q2: Score de conduccion promedio por ciudad
# Equivalente MongoDB:
# db.vehicle_telemetry.aggregate([
#   { $group: { _id: '$location.city', score_prom: { $avg: '$driver_behavior.score' } } }
# ])
print('\nIoT-Q2: Score de conduccion por ciudad')
print('-' * 55)
q_iot2 = (df_iot.groupby('city').agg(
    lecturas     = ('vehicle_id', 'count'),
    score_prom   = ('score', 'mean'),
    pct_alertas  = ('has_alert', 'mean'),
    vel_prom_kmh = ('speed_kmh', 'mean'),
).reset_index())
q_iot2['score_prom']   = q_iot2['score_prom'].round(1)
q_iot2['pct_alertas']  = (q_iot2['pct_alertas'] * 100).round(1)
q_iot2['vel_prom_kmh'] = q_iot2['vel_prom_kmh'].round(1)
display(q_iot2.sort_values('score_prom', ascending=False))

IoT-Q1: Top 10 vehiculos con mas frenadas bruscas
-------------------------------------------------------

   vehicle_id  frenadas_bruscas
0          11                13
1         133                13
2         128                12
3          94                11
4          79                11
5         106                11
6          90                10
7         178                10
8          92                10
9          18                10

IoT-Q2: Score de conduccion por ciudad
-------------------------------------------------------

               city  lecturas  score_prom  pct_alertas  vel_prom_kmh
1       Guadalajara      1969        84.7         11.4          58.9
3            Puebla      2047        84.5         12.0          60.7
4           Tijuana      2012        84.4         12.0          60.0
0  Ciudad de Mexico      2024        84.3         11.8          59.2
2         Monterrey      1948        84.1         13.3          59.2

---
## Parte 8 - Reporte final

In [38]:
print('=' * 62)
print('  AVANCE 3 - DATA WAREHOUSE + ETL + IoT   REPORTE FINAL')
print('=' * 62)
print()

conteos = [
    ('dim_date',         df_etl['date_key'].nunique(),
     'Generada: 1 fila por dia del periodo 2023-2024'),
    ('dim_time',         df_etl['scheduled_time_key'].nunique(),
     'Generada: 1 fila por minuto-hora del batch'),
    ('dim_vehicle',      df_etl['vehicle_id'].nunique(),
     'PG vehicles + age_months + last_maintenance_date'),
    ('dim_driver',       df_etl['driver_id'].nunique(),
     'PG drivers + full_name + experience_months + performance_category'),
    ('dim_route',        df_etl['route_id'].nunique(),
     'PG routes + difficulty_level + route_type'),
    ('dim_customer',     df_etl['customer_name'].nunique(),
     'Derivada de deliveries (no hay tabla customers en PG)'),
    ('staging_trips',    df_etl['trip_id'].nunique(),
     'NUEVA: PG trips + trip_duration_hours + deliveries_per_hour'),
    ('fact_deliveries',  len(df_etl[df_etl['delivered_datetime'].notna()]),
     'JOIN de todas las tablas OLTP'),
    ('daily_kpi_summary', 1,
     'Resumen pre-calculado del batch (dashboards en <100ms)'),
]

print('TABLAS CARGADAS EN SNOWFLAKE / CSV:')
print('-' * 62)
for nombre, n, origen in conteos:
    tipo = 'HECHOS' if nombre == 'fact_deliveries' else 'DIM   '
    print(f'  [{tipo}] {nombre:<22} {n:>8,}  {origen}')

total = sum(n for _,n,_ in conteos)
print(f'\n  TOTAL DW                         {total:>8,} registros')

print()
print('TELEMETRIA IoT (MongoDB):')
print(f'  Documentos generados    : {len(docs_iot):,}')
print(f'  Frenadas bruscas        : {df_iot["harsh_braking"].sum():,}')
print(f'  Score prom conduccion   : {df_iot["score"].mean():.1f}/100')

print()
print('CORRECCIONES APLICADAS AL SCRIPT BASE:')
print(f'  OverflowError linea 145 : valid_to = {df_etl["valid_to"].iloc[0]} (date() Python puro)')
print(f'  Validaciones (no elimina): {(df_etl["data_quality_flag"]!="ok").sum()} registros marcados')
print(f'  #TO DO# extract         : query con 5 JOINs consolidados')
print(f'  #TO DO# load_dimensions : 6 dimensiones completas con MERGE')
print(f'  #TO DO# daily_totals    : CREATE TABLE + MERGE completados')
print(f'  staging_trips           : nueva tabla para trips en Snowflake')

print()
print('ARCHIVOS GENERADOS EN ./dw_data/:')
for archivo in sorted(os.listdir(OUTPUT_FOLDER)):
    ruta = f'{OUTPUT_FOLDER}/{archivo}'
    if os.path.isfile(ruta):
        print(f'  {archivo:<42} {os.path.getsize(ruta):>10,} bytes')

# Guardar resumen JSON para el README
resumen = {
    'fecha_ejecucion':    datetime.now().isoformat(),
    'dw_tables':          {n: rows for n,rows,_ in conteos},
    'iot_documents':      len(docs_iot),
    'on_time_rate':       float(df_etl[df_etl['delivered_datetime'].notna()]['is_on_time'].mean()),
    'avg_delay_minutes':  float(df_etl['delay_minutes'].mean()),
    'registros_marcados': int((df_etl['data_quality_flag'] != 'ok').sum()),
    'correcciones': [
        'OverflowError linea 145: date(9999,12,31) en lugar de pd.to_datetime',
        'Validaciones: data_quality_flag en lugar de eliminar filas',
        'extract_daily_data: query con 5 JOINs (completado #TO DO#)',
        'load_dimensions: 6 dimensiones completas (completado #TO DO#)',
        '_calculate_daily_totals: CREATE + MERGE (completados #TO DO#)',
        'staging_trips: nueva tabla para integrar trips en Snowflake',
    ]
}
with open(f'{OUTPUT_FOLDER}/avance3_summary.json', 'w') as f:
    json.dump(resumen, f, indent=2, default=str)
print('\nResumen guardado en dw_data/avance3_summary.json')
print('=' * 62)

==============================================================
  AVANCE 3 - DATA WAREHOUSE + ETL + IoT   REPORTE FINAL
==============================================================

TABLAS CARGADAS EN SNOWFLAKE / CSV:
--------------------------------------------------------------
  [DIM   ] dim_date                    697  Generada: 1 fila por dia del periodo 2023-2024
  [DIM   ] dim_time                  1,440  Generada: 1 fila por minuto-hora del batch
  [DIM   ] dim_vehicle                 182  PG vehicles + age_months + last_maintenance_date
  [DIM   ] dim_driver                  378  PG drivers + full_name + experience_months + performance_category
  [DIM   ] dim_route                    48  PG routes + difficulty_level + route_type
  [DIM   ] dim_customer            383,047  Derivada de deliveries (no hay tabla customers en PG)
  [DIM   ] staging_trips            99,950  NUEVA: PG trips + trip_duration_hours + deliveries_per_hour
  [HECHOS] fact_deliveries         400,000  JOIN de todas las tablas OLTP
  [DIM   ] daily_kpi_summary             1  Resumen pre-calculado del batch (dashboards en <100ms)

  TOTAL DW                          885,743 registros

TELEMETRIA IoT (MongoDB):
  Documentos generados    : 10,000
  Frenadas bruscas        : 988
  Score prom conduccion   : 84.4/100

CORRECCIONES APLICADAS AL SCRIPT BASE:
  OverflowError linea 145 : valid_to = 9999-12-31 (date() Python puro)
  Validaciones (no elimina): 0 registros marcados
  #TO DO# extract         : query con 5 JOINs consolidados
  #TO DO# load_dimensions : 6 dimensiones completas con MERGE
  #TO DO# daily_totals    : CREATE TABLE + MERGE completados
  staging_trips           : nueva tabla para trips en Snowflake

ARCHIVOS GENERADOS EN ./dw_data/:
  avance3_summary.json                              876 bytes
  ddl_tablas_adicionales.sql                      2,272 bytes
  dim_customer.csv                           26,483,437 bytes
  dim_driver.csv                                 36,110 bytes
  dim_route.csv                                   3,521 bytes
  dim_vehicle.csv                                11,254 bytes
  fact_deliveries.csv                        260,505,593 bytes
  staging_trips.csv                          10,224,390 bytes
  vehicle_telemetry_sample.json                  48,071 bytes

Resumen guardado en dw_data/avance3_summary.json
==============================================================

In [39]:
# DIAGNOSTICO DIRECTO — corre esto en celda nueva
import psycopg2, snowflake.connector, pandas as pd, logging
from datetime import date

logging.basicConfig(level=logging.DEBUG)  # nivel DEBUG para ver TODO

pg = psycopg2.connect(**PG_CONFIG)
sf = snowflake.connector.connect(**SNOWFLAKE_CONFIG)
cur = sf.cursor()

# Test 1: insertar dim_date
print("Test dim_date...")
cur.execute("DELETE FROM dim_date WHERE 1=1")
cur.execute("""
    INSERT INTO dim_date (date_key, full_date, day_of_week, day_name,
        day_of_month, day_of_year, week_of_year, month_num, month_name,
        quarter, year, is_weekend, is_holiday, fiscal_quarter, fiscal_year)
    VALUES (20240101, '2024-01-01', 1, 'Lunes', 1, 1, 1, 1, 'Enero',
            1, 2024, FALSE, FALSE, 1, 2024)
""")
sf.commit()
cur.execute("SELECT COUNT(*) FROM dim_date")
print(f"  dim_date: {cur.fetchone()[0]} filas")

# Test 2: insertar dim_vehicle con fecha como string
print("Test dim_vehicle...")
cur.execute("DELETE FROM dim_vehicle WHERE 1=1")
cur.execute("""
    INSERT INTO dim_vehicle (vehicle_id, license_plate, vehicle_type,
        capacity_kg, fuel_type, acquisition_date, age_months, vehicle_status,
        valid_from, valid_to, is_current)
    VALUES (1, 'ABC-123', 'Camion', 5000.0, 'Diesel',
            '2020-01-15', 52, 'active', '2024-01-01', '9999-12-31', TRUE)
""")
sf.commit()
cur.execute("SELECT COUNT(*) FROM dim_vehicle")
print(f"  dim_vehicle: {cur.fetchone()[0]} filas")

# Test 3: insertar dim_driver
print("Test dim_driver...")
cur.execute("DELETE FROM dim_driver WHERE 1=1")
cur.execute("""
    INSERT INTO dim_driver (driver_id, employee_code, full_name,
        license_number, hire_date, experience_months,
        driver_status, performance_category,
        valid_from, valid_to, is_current)
    VALUES (1, 'EMP001', 'Juan Perez', 'LIC001',
            '2020-03-01', 48, 'active', 'Medio',
            '2024-01-01', '9999-12-31', TRUE)
""")
sf.commit()
cur.execute("SELECT COUNT(*) FROM dim_driver")
print(f"  dim_driver: {cur.fetchone()[0]} filas")

pg.close()
sf.close()
print("\nTodos los inserts funcionaron correctamente")

2026-06-08 22:38:32,536  INFO  Snowflake Connector for Python Version: 4.6.0, Python Version: 3.14.3, Platform: Windows-10-10.0.19045-SP0
2026-06-08 22:38:32,538  INFO  Connecting to GLOBAL Snowflake domain

Test dim_date...
  dim_date: 1 filas
Test dim_vehicle...
  dim_vehicle: 1 filas
Test dim_driver...
  dim_driver: 1 filas

Todos los inserts funcionaron correctamente

In [40]:
# DIAGNOSTICO — corre esto antes del Run All
import snowflake.connector

print("Intentando conectar a Snowflake...")
try:
    sf = snowflake.connector.connect(**SNOWFLAKE_CONFIG)
    print(f"Conectado: {sf}")
    print(f"sf es None: {sf is None}")
    print(f"bool(sf): {bool(sf)}")
    
    cur = sf.cursor()
    cur.execute("SELECT CURRENT_DATABASE(), CURRENT_SCHEMA()")
    row = cur.fetchone()
    print(f"Base: {row[0]}  Schema: {row[1]}")
    sf.close()
    print("Snowflake OK")
except Exception as e:
    print(f"ERROR: {e}")

print(f"\nSNOWFLAKE_ENABLED = {SNOWFLAKE_ENABLED}")

2026-06-08 22:38:41,521  INFO  Snowflake Connector for Python Version: 4.6.0, Python Version: 3.14.3, Platform: Windows-10-10.0.19045-SP0
2026-06-08 22:38:41,524  INFO  Connecting to GLOBAL Snowflake domain

Intentando conectar a Snowflake...
Conectado: <snowflake.connector.connection.SnowflakeConnection object at 0x0000018D036A2900>
sf es None: False
bool(sf): True
Base: FLEETLOGIX_DW  Schema: ANALYTICS
Snowflake OK

SNOWFLAKE_ENABLED = True

In [41]:
query = """
SELECT
    d.delivery_id, d.trip_id, d.tracking_number,
    d.customer_name, d.delivery_address, d.package_weight_kg,
    d.scheduled_datetime, d.delivered_datetime,
    d.delivery_status, d.recipient_signature,
    t.departure_datetime, t.arrival_datetime,
    t.fuel_consumed_liters,
    t.total_weight_kg  AS trip_total_weight_kg,
    t.status           AS trip_status,
    v.vehicle_id, v.license_plate, v.vehicle_type, v.capacity_kg,
    v.fuel_type, v.acquisition_date, v.status AS vehicle_status,
    dr.driver_id, dr.employee_code, dr.first_name, dr.last_name,
    dr.license_number, dr.license_expiry, dr.phone, dr.hire_date,
    dr.status AS driver_status,
    r.route_id, r.route_code, r.origin_city, r.destination_city,
    r.distance_km, r.estimated_duration_hours, r.toll_cost
FROM deliveries d
JOIN trips    t  ON d.trip_id    = t.trip_id
JOIN vehicles v  ON t.vehicle_id = v.vehicle_id
JOIN drivers  dr ON t.driver_id  = dr.driver_id
JOIN routes   r  ON t.route_id   = r.route_id
WHERE t.status = 'completed'
  AND t.arrival_datetime IS NOT NULL
  AND t.fuel_consumed_liters IS NOT NULL
ORDER BY d.delivery_id
"""